### ISSUE TITLE
Find issues to resolve for this lesson

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-open-refine#10]
This lesson has now been migrated to the Library Carpentry organisation. Work should happen on THIS repo.

All the issues raised for this lesson are still on the old repo at https://github.com/data-lessons/library-openrefine-DEPRECATED/issues

Find issues to resolve *there* and fix them **here**.

**Comment by rovinghistorian** [comment]
Does lesson 9. Undo/redo make sense where it is, or would it make more sense to move it earlier (i.e. after lesson 4 when participants start modifying data)?

**Comment by rovinghistorian** [comment]
Would there be time in lesson 10--or would it be better as part of an advanced set of lessons--to discuss handling transforming messy dates?  (My use case:  a spreadsheet inventory with a column for dates, creators added data like 2/xx/1954 or 19?? in addition to 2/3/1934 and other data that was easier to transform/clean up.)

**Comment by ostephens** [comment]
I think a lesson on "Dates in OpenRefine" that could be optionally included would be v useful . Would be interesting to sketch out what could be in that - but would think about including:

* Using toDate and toString
* Using 'match' to work with messier dates
* Date facets
* Date specific GREL functions: datePart, diff, inc, now

**Comment by ostephens** [comment]
All issues on  https://github.com/data-lessons/library-openrefine-DEPRECATED/issues are closed, and I've created a new enhancement request #61 for the Dates question raised here.

So - closing this issue
