### ISSUE TITLE
Episode 6: Working with columns and sorting - no information on renaming columns

### ISSUE THREAD

**Issue by ebunge** [LibraryCarpentry/lc-open-refine#100]
The episode overview, key points and one of the headings all mention renaming a column, but the episode doesn't actually contain any information on how to do this.

I would suggest adding something like this:

You can rename a column by opening the drop-down menu at the top of the column and choosing `Edit column -> Rename this column`. You will then be prompted to enter the new column name.

**Comment by ostephens** [comment]
Thanks @ebunge - completely agree!

If someone were to do a Pull Request to add directions on renaming a column that would be great

**Comment by Biostew** [comment]
Hello - Has this issue been resolved? I will make a pull request if it isn't already in progress! Thanks! :)

**Comment by ostephens** [comment]
Closed by #103
