### ISSUE TITLE
Episode 11: Fix minor typo

### ISSUE THREAD

**Issue by jcoliver** [LibraryCarpentry/lc-open-refine#102]
The second point of the `match` part of the exercise appears to have a typo:

>In the Expression box type `value.match(/(.*),(.*)/)` The `/`, means you are using a regular expression inside a GREL expression. The parentheses indicate you are going to match a group of characters. The `.\*` expression will match any character...

I think the `.\*` should actually read `.*`

**Comment by ostephens** [comment]
Thanks @jcoliver - this definitely needs fixing. Would be very happy to see a PR to correct this

**Comment by libcce** [comment]
This has been fixed https://github.com/LibraryCarpentry/lc-open-refine/pull/111

**Comment by libcce** [comment]
Thanks @jcoliver!
