### ISSUE TITLE
Episode 13: Create Subheading out of "Using the ‘cross’ function to lookup data in other OpenRefine projects"

### ISSUE THREAD

**Issue by andreamedinasmith** [LibraryCarpentry/lc-open-refine#105]
I recommend making "Using the ‘cross’ function to lookup data in other OpenRefine projects" a subheading of "Extensions". Currently, it is at the same level and makes it seem like a different section. 

I looked at adding a third '#', but that seems to have given it a unique yellow header at the front. Maybe a bullet point would be good enough. 
---

**Comment by libcce** [comment]
Hi @andreamedinasmith is this what you were thinking?
https://github.com/LibraryCarpentry/lc-open-refine/pull/109

**Comment by ostephens** [comment]
@andreamedinasmith @libcce I don't think this is correct. "Using the `cross` function" is a separate section - it is not a subsection of "Extensions".

Happy to see the lesson re-organised to make this clearer, but I don't think making it a subsection is the right solution

**Comment by libcce** [comment]
Ah ha, that makes sense @ostephens! @andreamedinasmith thanks for the suggestion! For now, I'm going to close your issue and my PR based on @ostephens feedback. Thanks @ostephens!

**Comment by andreamedinasmith** [comment]
@libcce I had been thinking of something like that, but @ostephens is right the Cross function isn't the same as an extension...that said:

The text is unclear and if I felt they were related, but they actually are not I'm probably not the only one. 

I think the confusion comes from the fact that a specific extension is mentioned in this section.

**Comment by libcce** [comment]
@andreamedinasmith I may have closed this issue too soon... sorry about that @andreamedinasmith. But maybe a new issue is needed addressing the structure/formatting of this episode? Do you want to open another issue that addresses this and provide a possible solution to restructuring the episode? Thanks @andreamedinasmith!

**Comment by ostephens** [comment]
@andreamedinasmith completely agree - this is confusing. Actually to be honest the whole episode is a bit odd because the episode file is named `13-looking-up-data.md` but then title is `Advanced OpenRefine functions` - I suspect it was a result of the lesson re-organisation we did a while back

I think we should consider:
* Amending the title to be in line with the file name
* Making the 'Extensions' more of an informational point (suspect there is a box style we can use?) so it is there to explain after the mention of the VIB-BITS extension in the `Cross` section

**Comment by libcce** [comment]
So @ostephens, rename it to:

"Looking up data with a URL"? That sounds good to me. Anyone want to submit a PR?

Seems like there are two options regarding a box style to choose from, discussion and callout:
http://carpentries.github.io/lesson-example/04-formatting/index.html

Callout might be the best option?

**Comment by ostephens** [comment]
I think rename "Looking up data" - as that covers both by URL, Reconciliation and Cross

**Comment by ostephens** [comment]
I've extracted  the actions from this into a new issue to make it clear what needs doing. Closing this one now #189 exists
