### ISSUE TITLE
"Dates and Numbers" checklist swaps day & month

### ISSUE THREAD

**Issue by katrinleinweber** [LibraryCarpentry/lc-open-refine#106]
I mean this part:

https://github.com/LibraryCarpentry/lc-open-refine/blob/1aa5abfdd5a3019b15804dbd1c8b8038680af8e4/_episodes/10-data-transformation.md#L29-L39

If you view the `Date` column through a text facet, it becomes apparent that the date format is `dd/MM/YYYY`, not `MM/dd/YYYY`as the instructed, common transformation `To date` expects. Thus, the instructions should be changed to use the proper transformation `value.toDate("dd/MM/yyyy")`.

**Comment by libcce** [comment]
Thanks @katrinleinweber and sorry for the delay!

**Comment by katrinleinweber** [comment]
No problem :-)
