### ISSUE TITLE
Explain use of UTF-8 encoding in Episode 2. Importing data into OpenRefine

### ISSUE THREAD

**Issue by loadbrain** [LibraryCarpentry/lc-open-refine#110]
Hello,
As part of the checkout process I propose following to Chapter 2: Importing data into OpenRefine

In the practical part "Create your first OpenRefine project (using provided data)"
it is written under 4.:

> Click in the Character encoding box and set it to UTF-8

It would be nice to explain in more detail why to do this and provide an example

Proposal for suggested change:
Look at the names in the author colum on line 3,5, 7.
There are some strange characters appearing.
Click in the Character encoding box and set it to UTF-8
Look again at these names and realize the changes.
The file has to have the right character encoding to show the correct characters.

**Comment by ostephens** [comment]
@loadbrain thanks very much for this.

I think explaining why the character encoding box is set to UTF-8 is definitely a good idea. I usually explain this while doing this episode.

In terms of demonstrating this directly in the interface - unfortunately versions of OpenRefine vary in how well they detect the correct encoding in an uploaded file, and so you can't rely on the strange characters appearing unless you choose a version of OpenRefine where this problem occurs - in recent versions (3.1, 3.2) I don't see any problems with character encoding even before setting the encoding to UTF-8.

My preference would be that we put something explicit into either the episode or the instructor notes would be a really good idea - if anyone wants to do a pull request for a change like this it would be gratefully received. But I'd leave out anything that would require characters to be parsed incorrectly in the first place as it isn't possible to ensure this always happens across OpenRefine installations

**Comment by loadbrain** [comment]
@ostephens 
You're right, it does not make sense if OpenRefine varies in detecting the correct encoding.
Maybe it has something to do with the system/country settings of the OS rather than OpenRefine.
I am using version 3.2 and can see the strange characters in Windows 10 OS/german settings
Loading the same file in a Linux OS (Manjaro/german settings) with OpenRefine 3.2, no problem...

I think instructor notes is a good place

**Comment by libcce** [comment]
@loadbrain did you end up creating a PR to address this in the episode or the instructor notes? Thanks!

**Comment by loadbrain** [comment]
No, if you want, you can do it

**Comment by jas58** [comment]
Closing this issue, as the current lesson currently says:
4. Click in the Character encoding box and set it to UTF-8. This ensures that OpenRefine correctly interprets the imported data as UTF-8 encoded. If you don’t select this you may find that some special characters (e.g. smart quotation marks) are not displayed correctly.
