### ISSUE TITLE
Import/Export MARC data with MarcEdit into OpenRefine

### ISSUE THREAD

**Issue by loadbrain** [LibraryCarpentry/lc-open-refine#113]
As MarcEdit will become another lesson in LC and ME offers the opportunity to import/export data from/to OpenRefine, include an optional episode to this when teaching a Library Carpentry. ith MarcEdit and OpenRefine.
Like taking MARC Data, exporting to OpenRefine, do some editing there and import it back.

#https://github.com/LibraryCarpentry/lc-marcedit/issues/3#issuecomment-532575858

**Comment by libcce** [comment]
Letting @ostephens @abigailsparling @jenmawe know so it is on their radar. Hope the ME lesson is coming along well 😄

**Comment by enimsakont** [comment]
I know this is an older comment, but I just wanted to add my voice to say that I agree that this is a good idea. The interaction between MarcEdit and OpenRefine is useful to know, though of course, it will not fit all workshops if MarcEdit is not being taught. I am completing this comment as part of my instructor training checkout, so I will soon be a new Carpentries instructor, and I would love to be involved with developing the MarcEdit lesson, if any more help is needed.

**Comment by jenmawe** [comment]
@enimsakont Thanks for your comment. The interaction between MarcEdit and OpenRefine is definitely on our radar. As you highlight, MarcEdit has so many features and cool tools that one carpentry lesson can't do it all justice. We are looking into highlights or "more" type of sections beyond the basics. We also have a section on integrations.

**Comment by libcce** [comment]
@jenmawe is the MarcEdit lesson still under development? If so, that is great!

**Comment by jenmawe** [comment]
@libcce Yes! Owen, Abigail, and I are slowly developing the lesson. Owen is going to show Abigail and I how to work with GitHub webpages later on this month.

**Comment by ostephens** [comment]
The MarcEdit lesson is still, slowly, being developed. If anyone wants to jump in a help out on that it would be very much appreciated. However, I think this particular issue can be closed and if necessary picked up again when the MarcEdit lesson gets to a good state
