### ISSUE TITLE
Episode 4: Regular Expressions for Faceting and Filtering

### ISSUE THREAD

**Issue by angelsu618** [LibraryCarpentry/lc-open-refine#115]
The link to the regular expressions lesson currently leads to a 404 page. I believe that it should link to this: https://librarycarpentry.org/lc-data-intro/01-regular-expressions/

For learners who have not attended an Intro to Working with Data, a brief definition in the lesson itself might be helpful for the instructor who may not have to time to go through it. For example, "You can also use regular expressions in the filter. This is helpful if you want to search for any text that matches a general pattern rather than a specific string."

**Comment by libcce** [comment]
Thanks @angelsu618 for catching this. Flagging this for @ppival @sharilaster @ccronje @antonangelo we have to update the lc-data-intro links across some of the lessons as @ccronje pointed out earlier links will change!

**Comment by ccronje** [comment]
Thanks for the catch @angelsu618 
Have submitted a PR to fix https://github.com/LibraryCarpentry/lc-open-refine/pull/117

**Comment by ostephens** [comment]
Fixed by #117
