### ISSUE TITLE
Minor exercise correction (checkout related issues)

### ISSUE THREAD

**Issue by lrskjr** [LibraryCarpentry/lc-open-refine#126]
There exits an error in the exercises on this page that would be nice to get corrected: [https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html](
)

Go to this heading: **Joining the Subjects column back together**

Change is:
_The subject words/headings were previously delimited with the pipe ( | ) character
To join the split subject cells back to a single cell you need to:
Click the dropdown menu at the top of the Subjects column
Choose ‘Join cells->Join multi-valued cells’
In the prompt type the ( | ) symbol and click ‘OK’_

To this:

_The subject words/headings were previously delimited with the pipe ( | ) character
To join the split subject cells back to a single cell you need to:
Click the dropdown menu at the top of the Subjects column
Choose ‘**Edit** cells->Join multi-valued cells’
In the prompt type the ( | ) symbol and click ‘OK’_

All the best 
Lars Kjær
---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by ostephens** [comment]
Thanks very much @lrskjr - I've fixed that now
Generally for small factual corrections like this we are very happy to just get pull requests you don't need to raise an issue for it first (as long as you are comfortable doing a pull request - if you aren't then obviously raising an issue is the right thing to do)
