### ISSUE TITLE
LC - Open refine, a few text corrections

### ISSUE THREAD

**Issue by sophieelisabeth** [LibraryCarpentry/lc-open-refine#127]
**Advanced OpenRefine functions
**Looking up data from a URL****

EDIT: Typically this is a two step process **-** , firstly a step to retrieve data from a remote service, and secondly to extract the relevant information from the data you have retrieved.
**(comma instead of dash)**

EXISTING TEXT: To retrieve data from an external source, from the drop down menu at a column heading use the option ‘Edit column->Add column by fetching URLs’.
SUGGESTED TEXT (RE-WORDED FOR CLARITY): To retrieve data from an external source, use the drop down menu at any column heading and select ‘Edit column->Add column by fetching URLs’.
**Reconciliation services**

EXISTING TEXT: One of the most common ways of using the reconciliation option in OpenRefine is with an extension (see below for more on extensions to OpenRefine) can use linked data sources for reconciliation.
SUGGESTED TEXT: One of the most common ways of using the reconciliation option in OpenRefine is with an extension (see below for more on extensions to OpenRefine) **which** can use linked data sources for reconciliation.

EXISTING TEXT: There also exist extensions to do reconciliation against local data such as csv files
SUGGESTED TEXT (RE-WORDED FOR CLARITY): Other extensions are available to do reconciliation against local data such as csv files
**Reconcile Publisher names with VIAF IDs**

EXISTING TEXT: If you look at the Publisher column, you should see some cells have found one or more matches - the potential matches are show in a list in each cell. 
SUGGESTED TEXT: If you look at the Publisher column, you should see some cells have found one or more matches - the potential matches are **shown** in a list in each cell. 

EXISTING TEXT: We could do these one by one, but if we are confident with matches, there is an option to accept all:
SUGGESTED TEXT: We could do these one by one, but if we are confident with **the** matches, there is an option to accept all:

**Using the ‘cross’ function to lookup data in other OpenRefine projects**
EXISTING TEXT: The VIB-Bits extension adds a number of very useful functions to OpenRefine including a way of using the ‘cross’ function with simply point-and-click functionality which makes looking up data from other projects significantly simpler.
SUGGESTED TEXT: The VIB-Bits extension adds a number of very useful functions to OpenRefine including a way of using the ‘cross’ function with **simple** point-and-click functionality which makes looking up data from other projects **much easier**.
---

---

**Comment by libcce** [comment]
@sophieelisabeth sorry for the delay in getting back to you! If you want to give it a try, you can click on the improve this page link at the top of this page https://librarycarpentry.org/lc-open-refine/13-looking-up-data/index.html, make the changes above, and submit a pull request for us to review? Make sure you link to this issue so the pull request and the issue are linked. With some of these changes I don't see any issues. Thanks!

**Comment by sophieelisabeth** [comment]
Hi Chris,
I have submitted the pull request now.  Wasn't sure how to link issue and pull request so I quoted the issue number and details of the issue in the pull request description.  Sophie

**Comment by libcce** [comment]
Thanks @sophieelisabeth but I can't seem to find the PR here https://github.com/LibraryCarpentry/lc-open-refine/pulls ? Maybe the PR is sitting in your own forked repository?

**Comment by sophieelisabeth** [comment]
Hi Chris
Hopefully you can see it now.
Link to issue #127 #135
Cheers
Sophie

---

*SOPHIE WRIGHT (she/her)*
BA (Hons), MInfoStud
Librarian

*Monash University*
Library
13 College Walk, Clayton Campus
Clayton, VIC 3130
Australia

T:+61 3 9902 0051
E: sophie.wright@monash.edu

monash.edu/library

CRICOS Provider: Monash University 00008C/01857J

We acknowledge and pay respects to the Elders and Traditional Owners of the
land on which our four Australian campuses stand. Information for
Indigenous Australians <https://www.monash.edu/indigenous-australians>

*I'm an LGBTIQ Ally*
Find out more at monash.edu/ally

We're committed to diversity and inclusion
<https://www.monash.edu/about/diversity-inclusion>

**Comment by libcce** [comment]
PR merged. Thanks @sophieelisabeth !!!
