### ISSUE TITLE
Feedback from delivering OpenRefine in Durham

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/lc-open-refine#133]
Last week, @uom-nilani, @CarleneB and I delivered this workshop at [Durham, UK](https://philreeddata.github.io/2019-12-11-durham/). We condensed the workshop into one day and included as much as was practical that people could still retain what they learned. We would like to offer the following feedback.

- Overall it went really well. It was a good chance to show regex in action, shows why they might want to continue learning these tools and techniques.
- We thought that the undo/redo feature was introduced a little late. Has it moved? If it were shown earlier, it might help people's confidence if they make mistakes. 
- For the last, advanced episodes, many people found it difficult to imagine that they could ever get to that stage, it felt like a big step up and everything up until that point was achievable. We wonder if, when the workshop is condensed into one day, a screencast of these features would be useful for learners to be able to play back at a later date. The written instructions are not sufficient after the instructor has left, and having further examples to follow would be useful.

**Comment by ppival** [comment]
Thanks for the feedback @PhilReedData

**Comment by libcce** [comment]
Thanks for the feedback @partiecolored @uom-nilani and @CarleneB 😄 Regarding undo/redo, where would we include it,  if early. It appears here https://librarycarpentry.org/lc-open-refine/09-undo-and-redo/index.html which is later as you mention. Alternatively, we can add a note to instructors in instructors notes? The screencasts idea might be something for a sprint, hopefully there is one planned in the future. In the meantime, we might want to create a separate issue that speaks to this? CC @ostephens in case (webinar) videos are something they are thinking about per CZI?

**Comment by jas58** [comment]
Maybe in 03- Working with DAta
## The layout of OpenRefine
or
## Working with data in OpenRefine

This is the first time students would be in the screen that includes the left column.  

I might add:  under layout, a third sentence/paragraph:
OpenRefine comes with a safety belt: note the left column, currently empty. Note the four words at the top of the column:
Facet/Filter and Undo/Redo.  We will focus on the undo/redo button much later in the workshop; you are welcome to use it at anytime, as needed.

**Comment by jas58** [comment]
As this issue merged with #133 and PR#225, I will close this issue.
