### ISSUE TITLE
OpenRefine, Clustering - suggested revision

### ISSUE THREAD

**Issue by renetanner** [LibraryCarpentry/lc-open-refine#136]
In reviewing the lesson for [clustering](https://librarycarpentry.org/lc-open-refine/05-clustering/index.html) in Open Refine, I noticed that one of the objectives could be reworded for greater clarity. 

The objective is: 
"Use clustering to identify and fix replace varying forms of the same data with a single consistent value"

My suggested change is:
"Use clustering to identify and replace inconsistent forms of the same data with a single consistent value"

Thank you for considering.

**Comment by libcce** [comment]
Thanks @renetanner looks good to me! Do you want to give it a try and open a pull request? You can use the link at the top right corner that says improve this page with the pencil icon.

**Comment by renetanner** [comment]
Thank you Chris. I'll do that next. Thank you so much for the guidance.
Rene

**Comment by jas58** [comment]
Check out Sarah Stevens' 30 minute how to create a pull request [tutorial for the browser interface] (https://www.youtube.com/watch?v=BpEWDg8AbPc).
