### ISSUE TITLE
Setup page refers to deprecated version of Windows

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-open-refine#138]
The Open Refine lesson [setup page](https://librarycarpentry.org/lc-open-refine/setup.html) offers many ways of getting help.  One of them is to look for threads like Installing OpenRefine on Windows 7.

[Windows 7](https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information) has been deprecated. If we are to help people find help for specific versions of a given OS, I would suggest that we use active versions as examples.

**Comment by ostephens** [comment]
Agree that this reference is outdated and could be removed. If someone wants to do a PR for it, it would be very welcome (either removing the outdated reference or replacing it with a more up to date reference)

**Comment by evanwill** [comment]
@maneesha this was updated in PR #179 so no more reference to Win 7 👍
