### ISSUE TITLE
Broken link to OpenRefine Blog

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-open-refine#139]
On the [OpenRefine setup page](https://librarycarpentry.org/lc-open-refine/setup.html), one of the resources referred to is the OpenRefine Blog.

The link to this is broken. 
It is:  http://openrefine.org/category/edge-case.html
It should be: http://openrefine.org/category/blog.html

**Comment by ppival** [comment]
Thanks @maneesha, would you like to create a pull request for this change?

**Comment by maneesha** [comment]
Happy to - although I intentionally left it open and tagged "good first issue" as an easy way for people who are new to get started.

**Comment by libcce** [comment]
@karenword updated the blog link in another PR and I via another PR. Thanks @maneesha.
