### ISSUE TITLE
Suggested revisions to Transformations - Exporting 

### ISSUE THREAD

**Issue by abigailsparling** [LibraryCarpentry/lc-open-refine#143]
[Transformations - Exporting](https://librarycarpentry.org/lc-open-refine/12-export-transformation/index.html)
Noting the option to download the entire OR project in this lesson would be useful. In our sessions we had teams from multiple units across the library who wanted to know how to collaborate on OR projects.

**Comment by ostephens** [comment]
Thanks @abigailsparling.

I think this part of the lesson could do with an overhaul. Some initial thoughts about this:

* The heading should be "Exporting" not "Transformations - Exporting"
* The text should be expanded to explain the main export options (include the Project Export) in just a little more detail making sure the reasons for choosing the different exports are made clear and any terminology is clearly explained

**Comment by nesmithCP** [comment]
I am commenting as part of my Instructor Checkout process.

I agree with the suggestions to update the heading to just "Exporting" and to expand the text in this [episode](https://librarycarpentry.org/lc-open-refine/12-export-transformation/index.html). I used the format of the Importing episode page to create this draft, which needs further expansion from folks who have experience with these options. I left three asterisks*** on the below options where expansion for types of usage would be helpful.

[OpenRefineExportdraft.txt](https://github.com/LibraryCarpentry/lc-open-refine/files/6214663/OpenRefineExportdraft.txt)
--------------------------------------------------------------------------------


There are several options for getting your data out of OpenRefine now that you have cleaned up, standardized, and/or enhanced your data. You can export to a variety of file formats depending on what you need to do with the data next, including:

OpenRefine project archive to file: This option downloads a tar.gz version of your file which can easily be imported into OpenRefine again to work on later, or shared to be imported into OpenRefine on a different machine. (Remember that all OpenRefine work is local to your computer.)

_Standard text/values file types for viewing in other applications or for uploading elsewhere:_
TSV (tab-separated values)
CSV (comma-separated values)
HTML Table
Excel
ODF Spreadsheet

Custom tabular exporter***
SQL Exporter***
Templating***

_Options to convert in your browser for use in Google applications:_
OpenRefine project archive to Google Drive
Google Sheets

Wikidata edits***
QuickStatements file***
Wikidata Schema***

**Comment by futurescamp** [comment]
Hi, I am also commenting as part of my checkout procedure. Hope this is helpful!

To build on nesmithCP's suggestion here is some potential text for the Custom Tabular Exporter

Custom Tabular Exporter
For exporting only some of your data out of OpenRefine, you can use the Custom Tabular Exporter and choose which columns of data to export, what separator to use, and how to export the data.

After you choose the Custom Tabular Exporter option you will see a pop-up window with a set of tabs at the top. In the Content tab you can choose each column you want to export by checking or unchecking the box next to the column name. You can also select or deselect all of the column names by clicking the Select All and Deselect All buttons below the list of column names. You can also choose the order of by hovering over the column names and dragging and dropping them into whatever order you prefer. 

When each column name is selected you have the option of changing what data is exported for reconciled cells. These options are to the right of the column names and you have the option to export the matched entity's name or ID, or the cell's content. You also have the option to provide a link to the matched entity's page and to output nothing for unmatched cells. For the date/time data of reconciled cells you can choose the ISO standard or a locale format. 

Under the Download tab you have the option to export as a TSV, CSV, use a custom separator, a HTML table, or a proprietary Excel format.  You can also change the line separator, the text encoding standard, and choose to quote text.

The Upload tab allows you to upload your data to a Google spreadsheet, and the Option Code tab lets you save your export options for later by coping out the JSON code, saving it, and reusing it when using the Custom Tabular Exporter again.

**Comment by ostephens** [comment]
@nesmithCP @futurescamp it's always great to get contributions and improvements for the lesson - so thanks to you both.

My usual view is that where there are substantive suggestions for changing the lesson it's better for us if you are able to submit a pull request that makes the actual changes you are suggesting - this makes it much easier to compare what we already have with the proposed changes, and also to incorporate the changes that are being suggested.

If either of you were able to make these proposed changes into a pull request, that would be amazing. If not, don't worry - these suggestions will still be looked at - it just may take longer for them to be incorporated into the lesson

**Comment by emcaulay** [comment]
I address some of the topics raised in this issue in my PR #195

**Comment by jas58** [comment]
As two issues grew out of this discussion, may I close? Or should I refine which elements remain?  And would that need a new issue?
I'll link this year's video tutorial on creating PR's in Github, as well, in case a visitor is ready to propose where and what to change:
https://youtu.be/BpEWDg8AbPc

**Comment by kevintfrench** [comment]
Thank you, I think it's fine if you close the issue.
