### ISSUE TITLE
Lesson Contribution for Trainee

### ISSUE THREAD

**Issue by sheraaronhurt** [LibraryCarpentry/lc-open-refine#144]
This contribution is on behalf of a Trainee. 

The current key points are:

· Use the Create Project option to import data

· You can control how data imports using options on the import screen

I suggest we add:

· Several files types may be imported into OpenRefine.

**Comment by libcce** [comment]
LGTM @ostephens?

Thanks @sheraaronhurt!

**Comment by ostephens** [comment]
Definitely would be happy to see a pull request to add this

**Comment by libcce** [comment]
Yes, definitely a good first issue to leave open to anyone out there that wants to put in a pull request 😄

**Comment by libcce** [comment]
Thanks again @mikeadavidson!
