### ISSUE TITLE
Lesson Contribution for Trainee

### ISSUE THREAD

**Issue by sheraaronhurt** [LibraryCarpentry/lc-open-refine#148]
In the Faceting and Filtering section, under "Find all publications without a DOI" exercise, I noticed that it tells people to go to customized facets > facet by blank, when it should be facets > Customized facets > Facet by blank.

I think this could get confusing if there is a missing step in the flow. Please let me know if there is anything else I should do to fix this error in the lesson for checkout.

**Comment by libcce** [comment]
Thanks @sheraaronhurt this PR updates the lesson https://github.com/LibraryCarpentry/lc-open-refine/pull/149 and is ready for someone else to review.
