### ISSUE TITLE
Suggested revision to Transforming Strings, Numbers, Dates and Booleans

### ISSUE THREAD

**Issue by abigailsparling** [LibraryCarpentry/lc-open-refine#157]
In this [lesson](https://librarycarpentry.org/lc-open-refine/10-data-transformation/index.html), the section on Dates and Numbers utilizes the simple date format syntax to output the date in a human readable format. I think the lesson could benefit from an explanation of simple date format, or at least a reference/link to the Wiki page on [GREL Date Functions](https://github.com/OpenRefine/OpenRefine/wiki/GREL-Date-Functions) so participants understand why using "dd MMMM yyyy" outputs the year in this specific way.

**Comment by ostephens** [comment]
If someone were to put in a pull request for a change to achieve this then that would be great

**Comment by LindaKalinda007** [comment]
It might be worth noting the format with MMMM does not denote a numerical month. What comes first for open refine the date or the month. Would the package automatically know format based on country or regions? Perhaps and actual example such as "21OCTO2020" or 21 10 2021.

**Comment by curet** [comment]
just requested a pull request!

**Comment by jas58** [comment]
Reviewing older issue conversations. Part of this was addressed in a separate thread. 
As I read the 10th episode today, MMMM is translated as June in the second table.
If that is not sufficient, please follow up within 60 days.

**Comment by jas58** [comment]
@abigailsparling Hello, Abigail!  Our paths cross again!  We are hoping to clear out older issues as Carpentries rolls into a new system next year.  I can now put a name to a handle and wanted to check in.  Cordially, Jennifer

**Comment by abigailsparling** [comment]
The update to the lesson resolves this issue very thoroughly! I will close the issue.
