### ISSUE TITLE
Revisions for OpenRefine 3.4

### ISSUE THREAD

**Issue by derlandson** [LibraryCarpentry/lc-open-refine#160]
I am looking over the latest release 3.4 (now 3.4.1) and I'm noticing that the parsing options page includes a checkbox to apply a trim leading/trailing whitespace transformation on project creation. It seems to be checked by default.
<img width="1091" alt="Screen Shot 2020-09-25 at 8 19 28 AM" src="https://user-images.githubusercontent.com/60274012/94272190-5343e080-ff08-11ea-9e97-f3a61ec96152.png">

Personally I think it's a pretty good practice to implement right away. It takes care of a couple of tasks that I would be doing with most of my projects anyway so it is a good time saver.

The tricky part is that the [Introduction to Transformations](https://librarycarpentry.org/lc-open-refine/07-introduction-to-transformations/index.html) episode depends on whitespace being present to demonstrate how publisher data can be corrected ("MDPI AG" vs. "MDPI AG ").

Personally I see three options (though there may be more!) I'm wondering what the best way to proceed might be?
1. We could have the class deselect this option on purpose at the beginning of the lesson. Though doing so could unintentionally teach people that they should deselect this every time they start a project.

2. We could introduce an extra space in the source CSV data here and there i.e. "MDPI  AG" and demonstrate Edit cells -> Common transformations -> Collapse consecutive whitespace. I think this would keep the lesson fairly close to the original without jumping ahead and having to write out a transformation by hand.

3. We could demo a different common transformation?

**Comment by ostephens** [comment]
Thanks for this @derlandson and apologies you didn't get a response sooner. This issue was also reported in #169 and the solution was discussed there. The lesson has now been updated in line with these changes

Thanks again

Owen
