### ISSUE TITLE
Episode 2-importing data - suggested revision

### ISSUE THREAD

**Issue by erika-b** [LibraryCarpentry/lc-open-refine#161]
This is a suggested change to a lesson as part of checkout as a new instructor. [02-importing-data](https://librarycarpentry.org/lc-open-refine/02-importing-data/index.html )

I have found that simply opening Open Refine can be tricky for folks. I am recommending that we change the initial direction in this lesson from:
1. Once OpenRefine is launched in your browser, click Create Project from the left hand menu and select Get data from This Computer

to:
1. To launch OpenRefine, find the file in your Applications folder or file explorer. Click openrefine.exe (it may have the blue diamond icon), and wait for OpenRefine to launch in a browser window. Once OpenRefine is launched in your browser, click Create Project from the left hand menu and select Get data from This Computer

This addition could also be made to the [Setup](https://librarycarpentry.org/lc-open-refine/setup.html) instructions.

Would be curious about others' thoughts on if this would be helpful in the written directions or if there is a good video/screenshot documentation that could be easily linked here. 
Thanks!

**Comment by ostephens** [comment]
Since the way you run OpenRefine varies across platforms, I think a link to the official documentation here would be the best approach. I believe this should be part of the Setup instructions rather than in an episode. The relevant page in the official documentation is https://docs.openrefine.org/manual/running

If someone were to put in a PR to add this link into the Setup instructions that would be great

**Comment by saragon02** [comment]
Hi @erika-b and @ostephens, I've created this PR to address the issue: https://github.com/LibraryCarpentry/lc-open-refine/pull/245

**Comment by jas58** [comment]
Does the result in #245 suffice?  If not, please follow up in the next 60 days.

**Comment by jas58** [comment]
Seeing no additional comments, closing this issue, as addressed by PR #245
