### ISSUE TITLE
Swap out "Introduce..." from learning objectives

### ISSUE THREAD

**Issue by brianmcelwaine** [LibraryCarpentry/lc-open-refine#163]
This contribution is part of a checkout. 

In line with Part 1, point 7 of the Checkout procedure documentation, I think the Learning objectives for the following episodes could use improvement:

Transforming Strings, Numbers, Dates and Booleans
https://librarycarpentry.org/lc-open-refine/10-data-transformation/index.html 
Objectives:
Introduce data formats
Introduce Boolean values and how to run transformations based on them

Transformations - Handling Arrays
https://librarycarpentry.org/lc-open-refine/11-using-arrays-transformations/index.html
Objectives:
Introduce Arrays, and how to use them to run transformations in GREL

Advanced OpenRefine functions
https://librarycarpentry.org/lc-open-refine/13-looking-up-data/index.html
Objectives:
Introduce how to use URLs to fetch data from the web based on what’s in an OpenRefine project
Introduce how to parse JSON data returned by web services
Introduce how to use Reconciliation services
Introduce OpenRefine extensions

In line with contributing directions, I think the "Introduce" terminology should be replaced with what we want the learner to be able to do. I suggest the following:

Introduce data formats -> Work with and transform data types in OpenRefine to prepare data for analysis
Introduce Boolean values and how to run transformations based on them -> Create and run transformations based on Boolean values. 

Introduce Arrays, and how to use them to run transformations in GREL -> Explain what an array is in OpenRefine, and use them to run transformations in GREL. 

Introduce how to use URLs to fetch data from the web based on what’s in an OpenRefine project -> use URLs to fetch data from the web based on what’s in an OpenRefine project. 
Introduce how to parse JSON data returned by web services -> Use the parseJson function to introduce data returned by web services to OpenRefine. 
Introduce how to use Reconciliation services -> Explain and demonstrate the use of reconciliation services to retrieve data from a URL. 
Introduce OpenRefine extensions -> Add functionality to your OpenRefine installation using OpenRefine extensions. 

Thanks,

Brian

**Comment by ostephens** [comment]
These look like very sensible updates to the objectives. If someone were to create a PR to make these changes it would be very welcome
