### ISSUE TITLE
Handout creation?

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-open-refine#17]
History here: https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/60

**Comment by U2NG** [comment]
Is there a printable handout available for the OR lesson?  The handout link on the guide page https://librarycarpentry.github.io/lc-open-refine/guide/ is broken.

**Comment by libcce** [comment]
Hi @U2NG, we are using @pitviper6 @jt14den's notes/exercises https://hackmd.io/XiAf3_T9ShudmMB_wmTJYw for the Library of Congress workshop next week. I also noticed the broken link and wondered if we should update with the notes that Juliane and Tim use? Maybe they can respond?

**Comment by pitviper6** [comment]
The link isn't broken for me - I get a tips and tricks page. 
I can give you my notes, but they are VERY rough! Read them through carefully, they're definitely a species of shorthand so you need to know the lesson pretty well before using them, or add to them beforehand.  https://github.com/pitviper6/workshop-materials/blob/master/OpenRefine%20Instructor%20Workshop%20Notes.docx

**Comment by libcce** [comment]
I think this PR https://github.com/LibraryCarpentry/lc-open-refine/pull/28 may fix the link @U2NG @pitviper6

**Comment by ppival** [comment]
Can this be closed as in issue? Does [https://librarycarpentry.org/lc-open-refine/guide/](https://librarycarpentry.org/lc-open-refine/guide/) suffice? @weaverbel @U2NG @ostephens @ccronje @pitviper6

**Comment by pitviper6** [comment]
I think all of the issues here could be rolled into one "create a handout for advanced GREL functions with some exercises" 

Thoughts?

**Comment by ostephens** [comment]
@ppival I think the request here is for a handout for those following the lesson rather than for instructors. It's slightly hard to tell, but tracking back through the various linked issues in deprecated repos there is an equivalence drawn with this guide to Regular Expressions in the Data Intro lesson https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/reference.md

@pitviper6 I think this is a good idea, although I suspect we need to cover the basics of GREL as well as advanced (I never know where this line is drawn anyway!)

**Comment by libcce** [comment]
@ostephens @pitviper6 @partiecolored I wonder if this can be a project during the upcoming Sprint https://librarycarpentry.org/blog/2019/03/lc-mozilla-global-sprint/ It would be nice to have supplemental material/a hand out that covered basic to advanced GREL approaches.

**Comment by libcce** [comment]
@ostephens can we close this issue and point to a new issue that is more clear for the sprinters? So -> Create a cheatsheet-like handout for GREL functions with examples based on https://github.com/LibraryCarpentry/lc-data-intro/blob/gh-pages/reference.md and maybe adding another example like https://www.cheatography.com/davechild/cheat-sheets/regular-expressions/? ? Maybe we can also point to OpenRefine's GREL recipes for ideas?

**Comment by ostephens** [comment]
Close in favour of #62
