### ISSUE TITLE
Episode 11 of OpenRefine - disappeared from Schedule

### ISSUE THREAD

**Issue by chennesy** [LibraryCarpentry/lc-open-refine#176]
There seems to be an error that is causing the title of (and link to) episode 11 of OpenRefine to not show up in the [schedule view](https://librarycarpentry.org/lc-open-refine/). On the [episode 11 page](https://librarycarpentry.org/lc-open-refine/11-using-arrays-transformations/index.html), the Overview and Key Points sections appear to have no content.

**Comment by ostephens** [comment]
Thanks @chennesy - looks like an inverted comma was missed - I've done a quick fix which hopefully will resolve this!

**Comment by ostephens** [comment]
Looks like that fixed it
