### ISSUE TITLE
Suggested addition - Exiting OpenRefine correctly

### ISSUE THREAD

**Issue by mdriscollic** [LibraryCarpentry/lc-open-refine#177]
In the user manual for OpenRefine (https://docs.openrefine.org/manual/running), there is a section on how to exit OpenRefine while ensuring all changes to your project are saved. I think this would make a strong (yet) short addition to the curriculum - especially for those participants who are unfamiliar with using the command line and how to exit using this method. I've pasted the text from the User manual below:

Exiting
To exit OpenRefine, close all the browser tabs or windows, then navigate to the command line window. To close this window and ensure OpenRefine exits properly, hold down Control and press C on your keyboard. This will save any last changes to your projects.

**Comment by ostephens** [comment]
Sounds like a great addition - if someone would like to put forward a pull request to add this, it would be very welcome
