### ISSUE TITLE
GREL replace function - create an exercise?

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-open-refine#18]
Discussion here: https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/38

**Comment by ppival** [comment]
Seems like as per [https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/38](https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/38) this could be closed as an "issue"? @weaverbel @ostephens @ccronje @pitviper6

**Comment by libcce** [comment]
@ostephens created the issue and @ccronje left it open for further discussion. Would the two of you want to make an executive decision here? There was no further discussion.

**Comment by ostephens** [comment]
I think this could be handled by adding examples of GREL `replace` in the proposed cheatsheet #62 

I'm happy to close if other are. @ccronje @pitviper6 ?

**Comment by weaverbel** [comment]
I have created a grel value.replace cheatsheet. I will upload it for
comment.
Cheers Belinda

**Comment by ostephens** [comment]
I'm going to close this issue for now. If we feel differently once the cheatsheet is done, we can always revisit
