### ISSUE TITLE
Episode 13: Adding screen shots/additional instructions

### ISSUE THREAD

**Issue by CardiganQueen** [LibraryCarpentry/lc-open-refine#180]
Hello, 

Am working my way through OpenRefine and am having trouble understanding and making "**Retrieving journal details from CrossRef via ISSN**" ( [https://librarycarpentry.org/lc-open-refine/13-looking-up-data/index.html](https://librarycarpentry.org/lc-open-refine/13-looking-up-data/index.html) ) work. 

I feel the lesson could be enhanced with screenshots that illustrates where data goes in the dialog box and what it should ideally look like,  in much the same way Episode 2[ (Importing data into OpenRefine)](https://librarycarpentry.org/lc-open-refine/02-importing-data/index.html) has a screenshot illustrating the various options.

I've been trying to work through this exercise, by myself and with a colleague, and can't make it work and really don't know where I'm going wrong, 

Peggy

**Comment by ostephens** [comment]
Hi @CardiganQueen - could you give some more detail of where in the exercise you get stuck? What stage do you get to, and what happens / goes wrong.

This will help us make sure that improvements we make to the lesson are definitely going to be helpful

Thanks

**Comment by CardiganQueen** [comment]
Hi @ostephens  - I get up to the point where the user needs to enter a bunch of URLs in a dialog box

> https://github.com/CrossRef/rest-api-doc
> http://api.crossref.org/journals/1099-4300
> "https://api.crossref.org/journals/"+value

and in the User-Agent field their email address "; mailto:p.hsu@blahblah.edu.au"

A message flashes by very quickly and then I get nothing but a new empty column. 
I think I've tried doing this roughly a dozen times but can't tell what I'm doing incorrectly, and think that a screen shot might help newbies like myself.

**Comment by CardiganQueen** [comment]
OMG - finally worked it out. I was adding too many URLs in the Expression box. It has taken me more than a dozen attempts over a few days - I obviously thought that all the other URLs that are on the page need to be included in the Expression box. I would still suggest that a screen shot would be of use to helpless n00bs like myself.

**Comment by ostephens** [comment]
Thanks @CardiganQueen - I've done a PR to add a screenshot as you suggest
