### ISSUE TITLE
Index Note: OpenRefine appears to be compatible with Edge browser

### ISSUE THREAD

**Issue by morskyjezek** [LibraryCarpentry/lc-open-refine#181]
We had some questions about compatibility with the Edge browser in a workshop today during the OpenRefine lesson (https://morskyjezek.github.io/2021-03-30-usgs-online/). It seems the OR 3.4.1 is compatible with the Edge browser: https://docs.openrefine.org/manual/running/#starting-and-exiting - it may be a good idea to remove the note on the index.md page to show only IE is not compatible.

**Comment by bencomp** [comment]
I think this can be closed? I don't see IE mentioned in Setup or on the homepage.

**Comment by ostephens** [comment]
Thanks @bencomp - we removed this recently but didn't catch the issue
