### ISSUE TITLE
Checkout Lesson Contribution: Episode 1&2

### ISSUE THREAD

**Issue by Talishask** [LibraryCarpentry/lc-open-refine#192]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

Episode 1: Under "What should I know..." It says that the original data is not being modified and the files are saved locally. When I first read this I was confused about how to export it back into an Excel spreadsheet or other file format. It says how to do this later on in Episode, but I think for clarity's sake it would be good to add something like "After you're done, you can export your transformed data back into the original file format" to this part of episode 1.

In Episode 3, the alt text on the images just says "Rows" and "Records." According to https://www.w3.org/WAI/test-evaluate/preliminary/ a text alternative should convey the purpose of the image and provide an equivalent user experience. The alt text for these images could be changed to something like "Screen capture showing OpenRefine in Rows mode" and "Screen capture showing OpenRefine in Rows mode" to provide more context for someone who is not able to see the images.

**Comment by jas58** [comment]
Per the second comment for Episode 3: I'm trying to locate where alt-text happens.  I do not have a way to edit that file (that I could see).  Should we add text blocks:
Image 1: "Screen capture showing OpenRefine in Rows mode"
Image 2:  "Screen capture showing OpenRefine in Rows mode"

Personally, I cannot see what the image is supposed to indicate for me.  Should I be looking for a number or the inconsistent shading of rows?  The preceding sentence says "Note how the numbering has changed" but all I see are blank cells (lower rows?) of different quantities after each of the numbers, still in sequence.

Oh, so 1. how to add alt-text?
2. Or add sentence: " The difference between the two images below are 1. Rows with the same Title appear below each shared title, interrupted the numbered sequence in the third column from the left. Shared titles have the same shading, which may be very difficult to distinguish, but notice each star and flag in the leftmost columns indicates a new row, an item with a different author."

**Comment by jas58** [comment]
I'm trying the code suggested in #237 
![Alt text](/path/to/image)
