### ISSUE TITLE
Checkout Lesson Contribution: Wording suggestion

### ISSUE THREAD

**Issue by klbarnes20** [LibraryCarpentry/lc-open-refine#193]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

Suggestion for improving grammar in Library Carpentries > Open Refine > Lesson 13 - Advanced OpenRefine functions (Looking Up Data) > Retrieving journal details from CrossRef via ISSN

Delete: You should see a message at the top on the OpenRefine screen indicating it is fetching some data, and how far it has got.
Replace with: You should see a message at the top on the OpenRefine screen indicating that it is fetching some data and its progress.

**Comment by ostephens** [comment]
Thanks @klbarnes20 

I think the second half of the sentence could be clearer still to be honest. Progress in fetching data is shown as a percentage which I understand to be the number of rows for which data has already been fetched as a percentage of the total number of rows for which data is being fetched. I think we can be clearer about this. How does following phrasing seem?

"You should see a message at the top on the OpenRefine screen indicating that it is fetching the data, with progress shown as a percentage which represents the proportion of rows for which data has been successfully fetched."

**Comment by nkenssous** [comment]
I would agree with Ostephens but I would simplify more to:

"You should see a message at the top on the OpenRefine screen indicating that it is fetching the data, with progress showing the percentage of the proportion of rows of data successfully being fetched."

**Comment by nkenssous61** [comment]
Yes you may
