### ISSUE TITLE
Update Episode 9 to avoid the use of "simply"

### ISSUE THREAD

**Issue by Talishask** [LibraryCarpentry/lc-open-refine#194]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

For https://librarycarpentry.org/lc-open-refine/09-undo-and-redo/index.html

In the Undo and Redo episode the word "simply" appears in the following sentences:

- The way OpenRefine records the steps you have taken even allows you to take the steps you’ve carried out on one data set, and apply it to another data set by a **simple** copy and paste operation.
- The Undo/Redo panel lists all the steps you've taken so far. To undo steps, **simply** click on the last step you want to preserve in the list and this will automatically undo all the changes made since that step.
- "The remaining steps will continue to show in the list but greyed out, and you can reapply them by **simply** clicking on the last step you want to apply."

Since the instructor training posits that this language can be demotivating to learners, I propose that this word be removed from the lesson.

**Comment by Tetteh1** [comment]
The word 'simple' though can be demotivating in certain instances, can also encourage the learner to get involved. It invokes the idea that not everything is coded or command based but just copy and paste for example, can also be used

**Comment by ostephens** [comment]
Done thanks to @mahunterUSGS

**Comment by ostephens** [comment]
@Tetteh1 thanks for the comment. Given the instructor guidelines suggest avoiding this language, I've gone ahead and accepted the change to the language from @mahunterUSGS. I do think you make a good point though - I just think we need to find ways of encouraging the learner that avoids making other learners feel like they are failing if they don't find something "simple" when it's described like that in the text.
