### ISSUE TITLE
Library Carpentry: Open Refine: Data set - URL column has broken links

### ISSUE THREAD

**Issue by musicalssm** [LibraryCarpentry/lc-open-refine#198]
When working with the data in the authors column, I wanted to see how the names were written on the original articles.  I found broken links and received 404 errors for most of the articles where names were not transforming the way I intended.  Is there a way to update the URLs so that students can reliably check their metadata against the original document?  If I were to check the URLs could I submit an updated file to be used for this lesson
[doaj-article-sample.csv](https://github.com/LibraryCarpentry/lc-open-refine/files/7475679/doaj-article-sample.csv)

**Comment by ostephens** [comment]
@musicalssm thanks for reporting this (and sorry about the delay in getting back to you). Using the DOAJ ID (the long alphanumeric string at the end of the URLs) I used the DOAJ API (https://doaj.org/api/docs) to check each article in the data set and found 47 of the records did not have current DOAJ records. I've attached a list of the missing articles here
[doaj-missing-articles.csv](https://github.com/LibraryCarpentry/lc-open-refine/files/7617014/doaj-missing-articles.csv)

I suspect we could just remove these from the data file and the lesson would still work but someone would need to check if removing them would require an update to any of the episodes (e.g. if we state the number of rows in a particular filter, or rely on particular values being present in the file that are removed by removing these records).

If someone were willing to take this on I would be very happy to review a pull request to update the lesson

**Comment by sheishistoric** [comment]
@ostephens I took a brief look at the lesson. If we were to remove the 47 records that did not have current DOAJ records (as of 11/29/21), we would have to update the first solution of [episode 4](https://librarycarpentry.org/lc-open-refine/04-faceting-and-filtering/index.html):

> How many articles in the file don’t have a licence assigned? Answer: 6

There would be no articles without a licence if we removed the 47 records.

**Comment by ostephens** [comment]
Thanks so much for checking this @sheishistoric. I'm a bit reluctant to lose that aspect of the lesson (showing how blank cells appear in a text facet).

Be interested in hearing what others think @sheishistoric @musicalssm @partiecolored @ppival @kristindawn

**Comment by partiecolored** [comment]
I am going to be stepping away from my role as a maintainer for LC Open Refine. I just wanted to give the rest of y'all a heads up before I talk to the maintainer coordinator.

**Comment by jas58** [comment]
Given the potential for multiple changes, perhaps an instructor note would suffice? "Some articles' URLs may 404 when working in the author column."

**Comment by ostephens** [comment]
I think perhaps a more general comment somewhere to say that the data file was produced from the DOAJ in 2015 and that it may not reflect data currently available from DOAJ

**Comment by jas58** [comment]
Episode 2, correct? Adding an instructor note to row 34?
"The data for this lesson was pulled from DOAJ in 2015 and may not reflect the same data currently available from DOAJ on the day of your workshop."
Once I find the guide in here on how to craft instructor notes.
