### ISSUE TITLE
Expand "Using the ‘cross’ function" section

### ISSUE THREAD

**Issue by mfeustle** [LibraryCarpentry/lc-open-refine#204]
The last section in [Advanced OpenRefine Functions](https://librarycarpentry.org/lc-open-refine/13-looking-up-data/index.html) has room for considerable expansion:

It would be helpful to acknowledge or address in some way the fact that the VIB-Bits extension currently linked there runs into a security warning in Chrome.

It would also be useful to provide a full walk-through of the cell-cross function. That, of course, will require a dataset for comparison, though the DOAJ has furnished other data-dumps that could be adapted. Beyond that, the key points are that:

- Columns to be reconciled between projects must have same the name. 

- Comparison entails using "Add column based on this column" with the the GREL expression cell.cross("[OtherProject]","[ColumnName]").length()

- The output yields a column indicating where there are matches, which can be found in a large dataset by faceting that column.

**Comment by ostephens** [comment]
@mfeustle there is definitely much more to say about many functions of OpenRefine than is covered in the lesson. The limitation here is the time available - it does not seem practical to expand what is said about cross without reducing some of the other material in the lesson to keep the session within a 3 hour limit.

I'm in no way against having more material on 'cross' or other functions, but I think we need to consider how this fits into the lesson as a whole. Having a separate "advanced" (I dislike the term 'advanced' - it's really just 'more' ) OpenRefine lesson has been proposed in the past, and I still think this is a good idea if people have the time and energy to take it on.

**Comment by ostephens** [comment]
Just a specfic comment on some of the points you mention about `cross`:
> Columns to be reconciled between projects must have same the name.

This isn't the case - the columns can have different names

> Comparison entails using "Add column based on this column" with the the GREL expression cell.cross("[OtherProject]","[ColumnName]").length()

There are different ways of approaching this - I tend to use a Custom Text Facet rather than "Add column" but both are valid approaches.  This is also specific to checking the number of matches and that's not always the desired outcome - you can vary the expression for other purposes (like unique match, no match, at least one match, more than one match etc.)
