### ISSUE TITLE
Reconciliation and mention of LCSH in intro

### ISSUE THREAD

**Issue by mfeustle** [LibraryCarpentry/lc-open-refine#206]
[Introduction to OpenRefine](https://librarycarpentry.org/lc-open-refine/01-introduction/index.html) currently includes "Match local data up to other data sets, for example in matching local subjects against the Library of Congress Subject Headings" as one of the benefits of using OpenRefine. However, access to LCSH for reconciliation has evolved; at the moment, OpenRefine's own documentation does not list LCSH among its current list of "[reconcilable authorities](https://reconciliation-api.github.io/testbench/)."

If it is even possible right now, reconciling with LCSH is definitely not straightforward, and users might be disappointed that the lesson does not follow through on this possibility. One fix may be to change the LCSH reference in the introduction to VIAF for now, since the last episode in the lesson does address accessing VIAF.

**Comment by ostephens** [comment]
This is fair - reconciling with LCSH isn't straightforward (I had to do this recently and ended up downloading LCSH as RDF triples and then using the RDF extension and  it's ability to use triple file as a reconciliation source). I'd be very much in favour of changing this mention to a source more easily usable - VIAF or Getty seem like good examples.

If someone were to make a pull request with a change to this affect I'm very happy to review

**Comment by ostephens** [comment]
Closed by #207
