### ISSUE TITLE
Using GREL for names reversing

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-open-refine#21]
Lots of discussion on this here:

https://github.com/data-lessons/library-openrefine-DEPRECATED/issues/64

**Comment by ostephens** [comment]
Name reversal now included in episode on Arrays
https://github.com/LibraryCarpentry/lc-open-refine/blob/0965157376e81eeb43a2409e83dbfbd99acb4eaa/_episodes/11-using-arrays-transformations.md

**Comment by ostephens** [comment]
Thanks to @libcce for spotting this!
