### ISSUE TITLE
New OR version, impacts on lessons? 

### ISSUE THREAD

**Issue by rhizomed** [LibraryCarpentry/lc-open-refine#210]
I am wondering about potential impacts of the newest OR version ([3.5.0](https://github.com/OpenRefine/OpenRefine/releases/tag/3.5.0)) on lesson curricula. I haven't done any extensive comparisons myself to ensure that there are no discrepancies between the new version and existing instructions, screen shots, etc., but wanted to bring this to the attention of the maintainers. I am also curious about the process for ensuring that lessons stay current with new software versions. Thanks! 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by ostephens** [comment]
@rhizomed thanks for this - we definitely need to run through the lesson with the updated version (now 3.5.1, and I think 3.5.2 is likely to be released soon although very unlikely to include changes that affect the lesson directly)

To answer your question about keeping lessons current with software versions, I can only really answer for OpenRefine, but we state in the lesson which version it's been tested up to (in the 'Setup' details https://librarycarpentry.org/lc-open-refine/setup.html), and after a release eventually an issue like the one you've raised here will get filed and someone will volunteer to run through the lesson with the latest version and check whether there are any changes that need to be made). If so we'll get contributions through a pull request to make the necessary changes and also update the 'latest tested version' information in the Setup file.

**Comment by rhizomed** [comment]
@ostephens thank you for explaining the process, much appreciated!

**Comment by katrinleinweber** [comment]
[OR v3.6](https://github.com/OpenRefine/OpenRefine/releases) by now, see #242.

**Comment by jas58** [comment]
As @katrinleinweber's extensive work has been merged, I will close this issue.
