### ISSUE TITLE
Confusing wording to explain "Use character" setting on preview page

### ISSUE THREAD

**Issue by mollycastro** [LibraryCarpentry/lc-open-refine#211]
In episode two, "Importing data into OpenRefine," I found the wording of step 6 confusing. I would like to suggest that it is reworded to make the purpose of selecting this setting a little clearer. I propose that this be changed from the current wording: 

"OpenRefine will automatically select “Use character” to enclose cells containing column separators as this will place data in one cell where the values are enclosed in quotes from the source dataset."

to this (or something like it):
	
OpenRefine will automatically select “Use character” to enclose cells containing column separators (such as a comma) as part of their data. This will make sure that OpenRefine doesn't misinterpret any commas (or other characters) within the column data as a delimiter. Keep this option selected. 
	
I would also like to suggest that this setting be circled in red on the lesson graphic like other settings discussed in the lesson are. This way it won't be missed by an instructor who is quickly referencing the graphic about what settings to cover while teaching. 

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by ostephens** [comment]
Thank you @mollycastro - this seems like a very good suggestion.

If anyone was able to make these changes and do a pull request, I'd be very happy to review

**Comment by nachi0310** [comment]
HI @ostephens , I would like to fix this issue. could you please assign it to me?

**Comment by ostephens** [comment]
@nachi0310 thank you 🙏  - it's assigned to you

**Comment by nachi0310** [comment]
@ostephens I have raised a PR. please let me know if there are any changes i need to do in this PR
