### ISSUE TITLE
OpenRefine sorting (checkout)

### ISSUE THREAD

**Issue by karenword** [LibraryCarpentry/lc-open-refine#217]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

------------------------

Greetings, I am emailing you instead of adding my comment to Github because this lesson required creating a new fork, which I am not comfortable doing. https://librarycarpentry.org/lc-open-refine/06-working-with-columns/index.html

For the OpenRefine Columns & Sorting lesson, the very end Key Points only list three for the lesson. The last of which is:
The original order of rows in OpenRefine is maintained during a sort until you use the option to Reorder Rows Permanently

However, the lesson doesn't really highlight this well but just casually mentions it. My suggestion is to add another statement after mentioning it in the Sort Columns section. The current statement is

> Unlike in Excel, 'Sorts' in OpenRefine are temporary - that is, if you remove the Sort, the data will go back to its original 'unordered' state. The 'Sort' drop-down menu lets you amend the existing sort (e.g., reverse the sort order), remove existing sorts, and/or make sorts permanent.

Add a statement:

> To make a sort permanent, choose Reorder Rows Permanently from the Sort drop-down menu.

I did not really understand this until I did a super deep dive in the lesson and I think this statement would help highlight the Key Point with more clarity.

Or to connect them you could add the bold to the Key Point:
The original order of rows in OpenRefine is maintained during a sort until you use the option to Reorder Rows Permanently **from the Sort drop-down menu**

**Comment by bencomp** [comment]
Those are great points! I taught the DC OpenRefine for Social Sciences lesson today and now realise how I could have explained sorting better. I now think sorting is such a common (exploratory) operation, that making each sorting change permanent directly could create a very long list of actions in the Undo/Redo tab. Because choosing 'Reorder Rows Permanently' is reversible through the undo option.

**Comment by jas58** [comment]
@karenword Thank you for making a suggestion to improve the Library Carpentry Open Refine lesson.  May I share a newer [tutorial on suggesting these edits in Github](https://youtu.be/BpEWDg8AbPc)? Then we can see where you are in the episode.
