### ISSUE TITLE
Clarify Rows vs Records

### ISSUE THREAD

**Issue by jas58** [LibraryCarpentry/lc-open-refine#227]
Add a (few) sentence(s) either to the the instructor notes or the main lesson text pointing to the Rows vs Records section in the [OpenRefine manual] (https://docs.openrefine.org/manual/exploring#rows-vs-records). 

You may refer to the discussion in [issue #84] (https://github.com/LibraryCarpentry/lc-open-refine/issues/84)

**Comment by stephanieuwa** [comment]
I would be happy to make this addition to the lesson text.
