### ISSUE TITLE
Add information on the use of Regular expressions in OpenRefine

### ISSUE THREAD

**Issue by ostephens** [LibraryCarpentry/lc-open-refine#231]
The current demonstration of using Regular Expressions in OpenRefine is artificial, and pending PR #188 is likely to be removed. However it seems important to include some mention in the lesson and is particularly important where the OpenRefine lesson has been taught alongside the LC Data Intro lesson as it gives a new context for techniques learnt in the earlier lesson.

Options (and we could adopt one or more of these) for doing this include:

1. Adding information to the Instructors Notes so it can be mentioned if appropriate
2. Adding an exercise that demonstrates the use of regular expressions in a realistic way
3. .... possible other options I've not thought of

Looking for feedback and suggestions for how we approach this

**Comment by ha0ye** [comment]
Some possibilities:
* extracting information from the citation field, such as the journal name or volume number (but OpenRefine already has the ability to split columns by a delimiter, and the sample data are already pretty well organized)
* searching on the title field (but not sure what example would work for a regex that wouldn't suffice for a simple text search)

**Comment by jas58** [comment]
Thank you for these ideas, @ha0ye.  Would you have time to create a pull request ([tutorial](https://www.youtube.com/watch?v=BpEWDg8AbPc))? Then we can commit more specifically on the phrasing and location.

**Comment by jas58** [comment]
Given changes from 188 and lack of follow up, closing issue.
