### ISSUE TITLE
Checkout training: Suggest adding more details to launching OpenRefine for setup.md

### ISSUE THREAD

**Issue by jenmawe** [LibraryCarpentry/lc-open-refine#234]
As I was practicing this lesson for the teaching demo, I noticed in the setup.md, [setup.md](https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/setup.md), that there is a comment on the command line window when you exit OpenRefine. However, there is no mention on how this window appears. I looked at the sections before Exiting OpenRefine and noticed that the instructions for running don't explain how to launch or run OpenRefine. I felt that more detail on how to run/launch OpenRefine that also introduces the appearance of the command line window would be great before it is mentioned in the section on Exiting.

**Comment by jas58** [comment]
Hi Jenmawe, Thanks for starting this discussion.  Would you have time to create a pull request with the edits you are thinking of so I can see where you mean?

**Comment by stephanieuwa** [comment]
Hi Jenmawe I can see what you mean about the lesson not initially mentioning the command line window. The lesson does say "Please follow OpenRefine's manual to [install](https://docs.openrefine.org/manual/installing) and [run](https://docs.openrefine.org/manual/running) it.", and the link for 'run' includes instructions that mention the command line window will open. Do you think that's enough, or should some of the text from OpenRefine's manual about running OpenRefine also be included in the Lib Carpentry lesson? The OpenRefine manual doesn't describe what a command line window looks like, or what it is.

**Comment by jas58** [comment]
Thank you, @stephanieuwa for following up with a suggestion.  Would you have time to create the pull request (tutorial video(https://www.youtube.com/watch?v=BpEWDg8AbPc))?

**Comment by stephanieuwa** [comment]
Sure, I have made a pull request!

**Comment by jas58** [comment]
does PR 253's merge mean this issue can be closed?

**Comment by stephanieuwa** [comment]
Hi jas58, yes it does. I'm not sure how to, or if I have permission to, close the issue myself. If you would be able to close the issue, could you please also remove the label 'Good first issue' so it no longer shows up in that list?

**Comment by ostephens** [comment]
Apologies that was my fault not closing this when I merged #253 
The default issue search on Github excludes closed issues, so we don't need to remove labels on them
