### ISSUE TITLE
Improve explanation of how Sorting works in OpenRefine

### ISSUE THREAD

**Issue by ostephens** [LibraryCarpentry/lc-open-refine#238]
Episode 6 "Working with columns and sorting" has a very brief explanation of sorting which could be improved to better capture the concept of "Sort" and "Reorder permanently" as well as how multi-column sorting works.

This issue is a stub to do this work - suggestions on wording/approaches can be discussed here and then a PR raised once we are clear on the approach

**Comment by jas58** [comment]
Nominate to close?

**Comment by jas58** [comment]
Given 183 has closed, were there outstanding thoughts not already addressed in PR #268 ?
