### ISSUE TITLE
consider  rephrasing "subject words" to "subject phrases" or just subjects

### ISSUE THREAD

**Issue by bjuhl** [LibraryCarpentry/lc-open-refine#261]
Hi newbie here submitting for instructor checkout but also I stumbled on this phrase.  

 In episode 3, the section / exercise Splitting Subjects into separate cells, the question is "How would you split these subject *words* into individual cells?" which at first I read as separating out each individual word using a fancy combo of pipes and spaces :)  Maybe instead just ask how to split the subjects into individual cells.  thank you this is a really tiny one!

**Comment by ostephens** [comment]
Thank you, @bjuhl  for this suggestion - I agree this would be a small but useful change. Would you have time to create the pull request ([tutorial video](https://www.youtube.com/watch?v=BpEWDg8AbPc))?

**Comment by bjuhl** [comment]
thank you @ostephens - done!  sorry it took a few days.

**Comment by jas58** [comment]
@ostephens I hope I merged this one right; closing the issue now.
