### ISSUE TITLE
02-importing-data.md line line 35

### ISSUE THREAD

**Issue by exn297** [LibraryCarpentry/lc-open-refine#263]
Hello,

I am doing my first contribution for instructor checkout and have a suggestion for file 02-importing-data.md on line 35.

For the part where it has "Click `Next»` - the next screen" I suggest deleting the "-" and instead putting in "and."

Thank you,
Erica

**Comment by jas58** [comment]
Hello Erica,
Thank you and welcome to Carpentries! May I share a very approachable [tutorial ](https://youtu.be/BpEWDg8AbPc)on how you can show us the exact line and make the edit for us to approve?

**Comment by exn297** [comment]
Hello Jennifer,

I watched the video and was able to make a new edit suggestion following the process in the video.

Thank you,
Erica


Erica Newcome (She/Her)

STEM & Interdisciplinary Research Librarian

University of Miami

***@***.***

305-284-4059

Book a ***@***.***/bookings/>


[cid:facb6497-e962-4122-b28b-f1ad32b051fc]
________________________________
From: Jennifer Stubbs ***@***.***>
Sent: Friday, December 2, 2022 9:46 PM
To: LibraryCarpentry/lc-open-refine ***@***.***>
Cc: Newcome, Erica ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [LibraryCarpentry/lc-open-refine] 02-importing-data.md line line 35 (Issue #263)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


Hello Erica,
Thank you and welcome to Carpentries! May I share a very approachable tutorial <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2FBpEWDg8AbPc&data=05%7C01%7Cexn297%40miami.edu%7C0e4c998466654f5f1a1108dad4d88d47%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638056323800099018%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wr4GXGmBkFc2tVCgnrBAOdxDmRSs1MmUNzT7I6F%2BgIg%3D&reserved=0> on how you can show us the exact line and make the edit for us to approve?

**Comment by jas58** [comment]
@ostephens Is this actually 265?  or is that a separate word edit?  I could not locate a 263 to verify.

**Comment by ostephens** [comment]
@exn297 is your edit in this branch on your repository? https://github.com/exn297/lc-open-refine/tree/patch-1

If so, to finish the process you need to do a "Pull Request" from that branch - this is illustrated from this part of the video tutorial that @jas58 linked above https://youtu.be/BpEWDg8AbPc?t=796

**Comment by exn297** [comment]
Hi,

It looks like what I edited was done. It was actually #265.

Thank you,
Erica
________________________________
From: Owen Stephens ***@***.***>
Sent: Monday, January 23, 2023 5:57 AM
To: LibraryCarpentry/lc-open-refine ***@***.***>
Cc: Newcome, Erica ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LibraryCarpentry/lc-open-refine] 02-importing-data.md line line 35 (Issue #263)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

@exn297<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fexn297&data=05%7C01%7Cexn297%40miami.edu%7C57c0cc5472604ac684d908dafd30a393%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638100682607524777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cps%2BIBleJGJb%2BF4GjFUcmJR5oXtLfLNqSCdbH0vp35w%3D&reserved=0> is your edit in this branch on your repository? https://github.com/exn297/lc-open-refine/tree/patch-1<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fexn297%2Flc-open-refine%2Ftree%2Fpatch-1&data=05%7C01%7Cexn297%40miami.edu%7C57c0cc5472604ac684d908dafd30a393%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638100682607524777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1qNBdBSZOwuR%2FbMciNIZAVnTFv13y0XRT%2FT52zNofbU%3D&reserved=0>

If so, to finish the process you need to do a "Pull Request" from that branch - this is illustrated from this part of the video tutorial that @jas58<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjas58&data=05%7C01%7Cexn297%40miami.edu%7C57c0cc5472604ac684d908dafd30a393%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638100682607524777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EBgRWPK5Xw4AgNN3D6q%2F8l3zKToVsAdDq2rhPm%2FK8G4%3D&reserved=0> linked above https://youtu.be/BpEWDg8AbPc?t=796<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2FBpEWDg8AbPc%3Ft%3D796&data=05%7C01%7Cexn297%40miami.edu%7C57c0cc5472604ac684d908dafd30a393%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C638100682607524777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4M2wl2jPEv4xiZ9sHABwrKDFvyrN92uvstJ33pTvASM%3D&reserved=0>
