### ISSUE TITLE
 Layout of OpenRefine, Rows vs Records - more viewable rows possible

### ISSUE THREAD

**Issue by rbzwillits** [LibraryCarpentry/lc-open-refine#264]
In the "Layout of OpenRefine, Rows vs Records" episode, under heading https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html#the-layout-of-openrefine , it reads, "OpenRefine only displays a limited number of rows of data at one time. You can adjust the number choosing between 5, 10 (the default), 25 and 50 at the top left of the table of data." 

It is possible to view 100, 500, and 1000 rows now as well. This text should be updated as well as the screenshots which only reflect the option to view 5 10 25 and 50 rows.

**Comment by jas58** [comment]
Hi @rbzwillits,
Thank you and welcome to Carpentries! May I share a very approachable [tutorial ](https://youtu.be/BpEWDg8AbPc)on how you can show us the exact line and make the edit for us to approve?

**Comment by rbzwillits** [comment]
Yes indeed and many thanks!

**Comment by jas58** [comment]
@rbzwillits Happy New Year!  We are trying to wrap up 2022's issues.  Would you have time in the next 60 days to create this PR?

**Comment by rbzwillits** [comment]
Hi! Yes! I've been meaning to get to this I'll add it to my calendar thank
you for the reminder!
