### ISSUE TITLE
Step 6 under construction or needs removal?

### ISSUE THREAD

**Issue by rizzorini** [LibraryCarpentry/lc-open-refine#269]
I'm looking at step 6. It's currently partly complete (and it might just be my timing if someone is actively working on it now). Should it be hidden or flagged as 'under construction' for new users/trainers?

**Comment by ostephens** [comment]
Hi @rizzorini can you point me to the step you are talking about (which episode?)

**Comment by rizzorini** [comment]
Thanks @ostephens - my terminology is probably not yet properly precise! I have dragged two screenshots in the hope it will provide greater clarity. It's episode 6 itself; sitting between '5. Clustering' and '7. Introduction to Transformations.'

![openrefine 6](https://user-images.githubusercontent.com/111330809/214564945-170f7095-9b92-434b-9580-43bac65d2e2e.PNG)
![openrefine 6 part 2](https://user-images.githubusercontent.com/111330809/214564968-09f162ed-b5d5-4c24-a1d9-f9a3b37dcaac.PNG)

**Comment by ostephens** [comment]
Thanks @rizzorini it looks like a change to the file earlier this week broke the headings etc. I'll fix asap

**Comment by ostephens** [comment]
Have made a fix https://github.com/LibraryCarpentry/lc-open-refine/commit/e158d168f23bd6249639649047fb8cc6eaea3df8 - once the lesson is republished it should fix this

**Comment by ostephens** [comment]
Thanks so much @rizzorini . The fix has worked and now the lesson information displays correctly on the site. I think there might still be a little tidying up to do but the lesson is working again now so the immediate problem is solved.
