### ISSUE TITLE
Possible typo under Instructor Notes

### ISSUE THREAD

**Issue by jamornini1117** [LibraryCarpentry/lc-open-refine#271]
Under Instructor Notes, it looks like there may be a typo under the section "Poweful transformations" (https://librarycarpentry.org/lc-open-refine/guide/index.html#poweful-transformations).  It seems like Poweful should be Powerful.

**Comment by ostephens** [comment]
Thanks for spotting this - I've fixed it with https://github.com/LibraryCarpentry/lc-open-refine/commit/e1f52281ab77400372ad15b471ccf2bd5994da24
