### ISSUE TITLE
Scheduling early transition to Workbench

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/lc-open-refine#273]
Short version: **are you are willing to volunteer your lesson for early transition to The Carpentries Workbench 
infrastructure?**

---

Longer version below:

As I hope you are already aware, @zkamvar and the rest of the Curriculum Team are preparing to roll out the new lesson infrastructure, [The Carpentries Workbench](https://carpentries.github.io/workbench/), across all of The Carpentries official lessons in early May 2023. This means that all Data Carpentry, Library Carpentry, and Software Carpentry lesson repositories will be modified to adopt the new infrastructure at the end of this month.

As you might imagine, coordinating a rollout like this involves a large amount of time and effort, and one thing that will really help us to keep to the schedule and avoid disruption for the community is to be able to **prepare some lessons for 
transition before the 1st May deadline**.

With this in mind, **I invite you to volunteer to schedule an early transition for theis lesson repository.** If you expect to have time to adopt the Workbench version of the lesson repository in the next couple of weeks, please reply to let me know. As lesson Maintainers, these are the things you will need to be prepared to do for the transition:
1. **Be prepared to quickly merge pull requests from Zhian**. These pull requests will help update the lesson and aid the transition process.
2. **Close any outstanding pull requests.** Your repository currently has very few or zero open PRs, but we cannot rule out the possibility that someone will open more in the time between now and when the transition takes place. [Open PRs will be invalidated when the transition takes place](https://carpentries.github.io/sandpaper-docs/pull-request.html#transition-from-carpentriesstyles).
3. **Preview the lesson (in the https://github.com/fishtree-attempt organisation) when it is available**. Zhian will open an issue in your repository, tagging you when the preview is available. You should reply on that issue if you notice any problems with the Workbench version of the lesson site and repository in the preview.
4. Just before the transition happens, the repository will be temporarily set as read-only and an issue will be opened (see an example from the Maintainer Onboarding curriculum: https://github.com/carpentries/maintainer-onboarding/issues/69) 
5. After the transition, **delete and recreate any forks and local clones** you have of the repository and then **confirm that you have done so** (you will be given specific instructions in an issue).

If you are willing and able to help us ensure a smooth rollout of the Workbench, please reply to let me know that you are happy to volunteer your lesson for early transition. If there is a specific date you would like the transition to take place (or that we should avoid), please also mention that.

**Comment by zkamvar** [comment]
Thank you for participating in the early transition to The Workbench. I have been able to render a preview of your lesson at https://fishtree-attempt.github.io/lc-open-refine.

I am tracking issues for your lesson in https://github.com/carpentries/lesson-transition/issues/65. I will be updating the preview next week as I work on any remaining issues. 

Please inspect the preview and make note in https://github.com/carpentries/lesson-transition/issues/65 if you see anything that needs to be fixed (e.g extra templating, narrow tables, or malformed text).

**Comment by ostephens** [comment]
@zkamvar while reviewing the preview I found an absolute link to the lesson setup page that should be a relative link in the lesson - does this kind of issue need correcting now, or just something to tidy up after transition?

**Comment by zkamvar** [comment]
Hello, 

We will transition this lesson on the first of May.

**Comment by zkamvar** [comment]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @jt14den (admin)
 - [ ] @jezcope (admin)
 - [ ] @ostephens (admin)
 - [ ] @laufers (push)
 - [ ] @cmacdonell (admin)
 - [ ] @chennesy (push)
 - [ ] @weaverbel (admin)
 - [ ] @annajiat (push)
 - [ ] @drjwbaker (admin)
 - [ ] @ccronje (admin)
 - [ ] @U2NG (admin)
 - [ ] @pitviper6 (admin)
 - [ ] @PhilReedData (push)
 - [ ] @ragamouf (push)
 - [ ] @jas58 (push)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
The deed is done. The infrastructure takes a few minutes to bootstrap and cache the packages for the lesson build. Once the build is done, I will switch github pages to deploy from the `gh-pages` branch and you will have your workbench lesson. 

Thank you all for your enthusiasm and your patience!

**Comment by zkamvar** [comment]
The Workbench version is now live: https://librarycarpentry.github.io/lc-open-refine/

In addition, here is [map of commits that were changed during the transition](https://github.com/carpentries/lesson-transition/blob/release_lc/lc-open-refine/release/librarycarpentry/lc-open-refine-commit-map.hash)

**Comment by jas58** [comment]
Thank you @zkamvar and @tobyhodges ! I'll close this thread.

**Comment by ostephens** [comment]
I am ready for write access :rocket:

**Comment by zkamvar** [comment]
@ostephens, access granted!

**Comment by PhilReedData** [comment]
I am ready for write access :rocket:

**Comment by zkamvar** [comment]
Hi @PhilReedData, thank you for following up. To shore up the security of the lesson repositories, the Curriculum Team would like to use this opportunity to tidy up the access levels we are providing to community members across the various repos. According to our records, you're not a Maintainer on this lesson, but I think you had previously been granted write access to the repository in your capacity as a LibraryCarpentry Curriculum Advisor.

For now, we are going to provide write access only to Maintainers---though that decision will be open to review, so please let us know (@ me or LibraryCarpentry/core-team-curriculum) if this interferes with the CAC's ability to perform their duties.

**Comment by jas58** [comment]
I am ready for write access 🚀

**Comment by zkamvar** [comment]
@jas58 access granted!

**Comment by ErinBecker** [comment]
@zkamvar - I am re-closing this issue as both of the Maintainers for this lesson now have access.
