### ISSUE TITLE
Link to Google group in Setup.md needs replacing with new forum URL

### ISSUE THREAD

**Issue by ostephens** [LibraryCarpentry/lc-open-refine#275]
The OpenRefine forum has moved from Google Groups to Discourse. The new URL is https://forum.openrefine.org

Mentions of the old Google Group in Setup (and if repeated elsewhere) should be updated to the new URL (although the old Google Group URL may still be useful for referring to older posts)

**Comment by AlexanderTarler** [comment]
On it! Please assign it to me :)

**Comment by AlexanderTarler** [comment]
Pull request sent yesterday, unsure if I need to alert anyone :) First time trying out issues!

**Comment by jas58** [comment]
Thank you, @AlexanderTarler . I see it was completed by PR#276 and will close this.
