### ISSUE TITLE
Broken URLK

### ISSUE THREAD

**Issue by jeboden** [LibraryCarpentry/lc-open-refine#278]
This [link](https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth) in Episode 5 Clustering is broken.  https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth

You can get the information [here](https://openrefine.org/docs/technical-reference/clustering-in-depth) now. https://openrefine.org/docs/technical-reference/clustering-in-depth

**Comment by jeboden** [comment]
Thank you!  I am still learning Github.

**Comment by yadlra** [comment]
opened a pull request ready for review! https://github.com/LibraryCarpentry/lc-open-refine/pull/279

**Comment by yadlra** [comment]
> opened a pull request ready for review! #279

ooops, because it's my first contribution I think it will be reviewed by the training progress team!?

**Comment by ostephens** [comment]
Thanks @yadlra @jeboden 

@yadlra no additional checks needed from this side - the PR is all good - but if the training progress team need to review for the purposes of instructor / contributor training for you then you can still point them at the PR - they don't need to approve but just see that it happened OK etc.
