### ISSUE TITLE
New OpenRefine versions in setup.md

### ISSUE THREAD

**Issue by myqua** [LibraryCarpentry/lc-open-refine#30]
The lesson recommends OpenRefine 2.7, but the OpenRefine download page has versions 2.8 and 3.0 only. I'm sure a student could hunt down 2.7, and perhaps update the setup.md link with a download page that has the older version, but it's probably best to keep this lesson updated with the latest versions as they come out. 

I can test the lesson in version 3.0 and alert you to any problems I come across.

**Comment by ostephens** [comment]
@myqua I'm pretty confident we could update this to a recommendation to use 3.0 - I've worked through most of the lesson with 3.0 and haven't yet seen any problems.

If you are able to confirm it works without a problem we should definitely update the lesson to use the latest version

**Comment by libcce** [comment]
I haven't noticed anything that needs updating and I recently taught OpenRefine at UNC. @jt14den @pitviper6 have you noticed any problems with the newest version?

**Comment by kristindawn** [comment]
I taught the lesson yesterday and when you go through the beginning of the arrays section and find all of the entries in Author with "," a lot of the people in the group didn't have "true" or "false" in the custom text facet. Instead it just said ("boolean"), which applied to all 1001 entries. I just tried it on my computer on 3.1 (I taught with 2.7) and it gave the same problem. Has anyone else seen this?

**Comment by ostephens** [comment]
Thanks for catching this @kristindawn 

There is a change in OpenRefine 3.1 which means the lesson needs updating to use:
```
value.contains(",").toString()
```

**Comment by ostephens** [comment]
Created issue for that

**Comment by partiecolored** [comment]
I created a pull request to update the version #38

**Comment by ostephens** [comment]
Fixed by #33 and #38 - thanks @kekoziar and @partiecolored respectively
