### ISSUE TITLE
Update Clustering In Depth link

### ISSUE THREAD

**Issue by srappel** [LibraryCarpentry/lc-open-refine#317]
### What is the problem?

The current link in 05-clustering links to https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth but that page then redirects to https://openrefine.org/docs/technical-reference/clustering-in-depth

### Location of problem (optional)

/05-clustering.html

**Comment by jas58** [comment]
Thank you, Stephen Rappel for catching that.  I created a PR #318 . Owen can review it by the end of next week.
