### ISSUE TITLE
Dead external link in instructor notes to handout 

### ISSUE THREAD

**Issue by PhilReedData** [LibraryCarpentry/lc-open-refine#325]
### What is the problem?

In the tips and tricks section of the [Instructor Notes](https://github.com/LibraryCarpentry/lc-open-refine/blob/main/instructors/instructor-notes.md) page, there is a link [Introduction to OpenRefine by Owen Stephens](https://www.meanboyfriend.com/overdue_ideas/wp-content/uploads/2014/11/Introduction-to-OpenRefine-handout-CC-BY.pdf) which no longer resolves. Suggest a new URL is found for the link else remove it.

### Location of problem (optional)

https://github.com/LibraryCarpentry/lc-open-refine/blob/main/instructors/instructor-notes.md

**Comment by ostephens** [comment]
It looks like the update to the new workbench incorrectly changed the link from `http` to `https`. Restoring the `http` will fix the link

**Comment by PhilReedData** [comment]
Ah, an easy fix! Well spotted, thank you.
