### ISSUE TITLE
In Lesson 11 (arrays) the Custom Facet needs to explicitly covert boolean .toString()

### ISSUE THREAD

**Issue by ostephens** [LibraryCarpentry/lc-open-refine#33]
Reported by @kristindawn in #30 

For OpenRefine 3.1 upwards list/text facets don't automatically convert numbers, dates or booleans to strings for the facet. This means the conversion has to be done explicitly by the user when they want to see (e.g.) booleans listed as true/false rather than just getting a count of the number of boolean values.

Lesson needs updating to use 
```
value.contains(",").toString()
```

**Comment by luban19p** [comment]
Thank you! Yes, I've just come across the same issue using OpenRefine 3.1
:)

**Comment by kekoziar** [comment]
This error is first encountered in the exercise `Find Reversed Author Names` in Lesson 10. Transforming Strings, Numbers, Dates and Booleans.

**Comment by ostephens** [comment]
Closed by #35
