### ISSUE TITLE
Latest OpenRefine version 

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-open-refine#342]
### What is the problem?

The [installation instructions](https://librarycarpentry.org/lc-open-refine/index.html#installing-and-running-openrefine) say this lesson has been tested with the most recent version of OpenRefine, 3.7.7.  However, on the downloads page, there is a version 3.7.9 and 3.8.0.

**Comment by jas58** [comment]
Hi Maneesha, Thank you for writing.  Unfortunately, this is correct.  I have not had the time to test the lesson since the 3.7.7 update.  If you are able to confirm all the steps of the lesson populate correctly with newer versions, please advise.

**Comment by maneesha** [comment]
In that case, we may want to note that we acknowledge that 3.7.7 is not actually the most recent version (as the lesson says that it is).
