### ISSUE TITLE
Update setup.md to remove mention of older versions of OpenRefine

### ISSUE THREAD

**Issue by ostephens** [LibraryCarpentry/lc-open-refine#39]
In `setup.md`

- [ ] Remove mentions of OpenRefine 2.x versions
- [ ] Remove information about using google-refine.exe which is not valid after v2.5
- [ ] Add a direct encouragement to upgrade to the tested version

**Comment by katrinleinweber** [comment]
Alternatively, all mentions of "2.x" could be removed in order to present only one version to learners and thus encourage them to upgrade (assisted by workshop instructors & helpers if necessary) to the version this lesson recommends.

**Comment by ostephens** [comment]
Agreed. So this task becomes:

* Remove mentions of OpenRefine 2.x versions
* Remove information about using `google-refine.exe` which is not valid after v2.5
* Maybe add a direct encouragement to upgrade to the tested version?

**Comment by katrinleinweber** [comment]
We could move these [tasks into](https://help.github.com/en/articles/about-task-lists#creating-task-lists) the 1st post, and [hide our two comments](https://help.github.com/en/articles/managing-disruptive-comments#hiding-a-comment) as resolved or outdated ;-)

**Comment by jyssy** [comment]
I submitted a pull request on setup.md with a few changes (all three of the items mentioned above)

**Comment by libcce** [comment]
Closing per https://github.com/LibraryCarpentry/lc-open-refine/pull/63
