### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [LibraryCarpentry/lc-open-refine#40]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by libcce** [comment]
I believe we can release this lesson, what does everyone @ppival @ostephens @partiecolored @pitviper6 @kristindawn @ccronje think? Vote with a thumbs up on the initial issue above if you think so. This is one of the most stable lessons in Library Carpentry and it would be nice to give credit to all of the contributors 😃 To start, I checked the lesson links and made the following PRs: 

* https://github.com/LibraryCarpentry/lc-open-refine/pull/42
* https://github.com/LibraryCarpentry/lc-open-refine/pull/43
* https://github.com/LibraryCarpentry/lc-open-refine/pull/44

Otherwise, all the other links work.

**Comment by libcce** [comment]
Regarding the instructor notes, I've submitted https://github.com/LibraryCarpentry/lc-open-refine/pull/45. I created a draft md in 'files' from my instructor outline/notes for a workshop I taught at UNC https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/files/draft-instructor-notes.md. I wonder if others who have taught OpenRefine recently can add/modify it @annaoates @JordanPedersen @rwangca @pitviper6 @JoshuaDull @mpfl ?

**Comment by libcce** [comment]
I checked off "Call out boxes (exercises, discussions, tips, etc) render correctly" since all appear to work properly.

**Comment by partiecolored** [comment]
I checked off the items about questions, objectives, and key points, and instructor notes

**Comment by ostephens** [comment]
All PRs by @libcce to fix lesson links now merged - so have checked that off

**Comment by ostephens** [comment]
All episodes have timings, so the lesson schedule displays correctly. Have checked that off

**Comment by libcce** [comment]
@fmichonneau the OpenRefine lesson will be ready for The Carpentries lesson release. 3 of the lesson Maintainers have voted to do this. We've already started to check off items on the release list as well.

**Comment by ErinBecker** [comment]
Awesome! Thanks @libcce  for letting us know.

**Comment by libcce** [comment]
Checked off:
Example code chunks run as expected
Challenges / exercises run as expected
Challenge / exercise solutions are correct

Raised issue https://github.com/LibraryCarpentry/lc-open-refine/issues/65 and two PRs https://github.com/LibraryCarpentry/lc-open-refine/pull/66 and https://github.com/LibraryCarpentry/lc-open-refine/pull/64 with minor corrections.

**Comment by libcce** [comment]
Setup has recently been updated:
- language asking people to download the latest tested version
- troubleshooting links
Checked off!

**Comment by libcce** [comment]
For the last item, file structure, do we need the autumn and spring images in the files folder? https://github.com/LibraryCarpentry/lc-open-refine/tree/gh-pages/files
Otherwise, I think everything else checks out.

**Comment by ostephens** [comment]
Thanks @libcce done a PR to remove those files

**Comment by libcce** [comment]
@ostephens all set then! List is checked off @ErinBecker!

**Comment by jyssy** [comment]
Wow - awesome. I had planned to come back to this next week when a little more bandwidth opened. Super

**Comment by libcce** [comment]
Oh! I forgot @jyssy! Any interest in the SQL lesson 😉 We need help there 😄

**Comment by jyssy** [comment]
Let me look... thanks

**Comment by ostephens** [comment]
Thanks to all who helped with this and to @libcce for keeping us at it until we got over the line :)

**Comment by ErinBecker** [comment]
Awesome work @LibraryCarpentry/lc-open-refine-maintainers  and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3266144

**Comment by libcce** [comment]
Congrats again everyone!

**Comment by ostephens** [comment]
@fmichonneau Can I ask a question about the people listed as contributors and the way the citation is done? 

I have to admit this is a little self interested as I'm a little bit frustrated not to be listed as one of the contributors, but listed as an Editor, and that the Editors aren't included in the citation. From what I can see, the same issue applies to all the editors with the exception of @ppival 

I can also see a lot of other people I know have contributed to the lesson missing from the list of creators, and I'm unclear why. I'm also unclear as to the ordering of the names in the list of creators.

I feel everyone who has contributed should be recognised for their contribution

**Comment by libcce** [comment]
Thanks @ostephens  for bringing this up. I noticed the same in other lessons as well. 
My understanding is that the authors would be listed by the number of commits (but accounting for commits that involve the lesson template). So it should be something like "James Baker, Owen Stephens, Chris Erdmann, Carmi Cronje, Juliane Schneider..." and instead it is "James Baker, Christopher Erdmann, Tim Dennis, mhidas, Daniel Bangert...". In my case, I've contributed to the lesson template as well, so I actually might be lower down the list. Regarding the order of the Editors/Maintainers, I'm not sure if I mind but we should have probably indicated how we wanted the order. I also noticed that the title and abstract include language that we are trying to get away from "...for Librarians" instead of more inclusive language. You can actually update the record with a new version... @fmichonneau I can help or if you want we can send to you our updated metadata?

**Comment by fmichonneau** [comment]
Hi @ostephens you are not listed among the authors as your preference in AMY is set to "No" for the option "Consent to include name when publishing lessons". If you wish to be included in future releases, please update your preference in your AMY profile. @ErinBecker and I are happy to edit the release to include your name as needed as Erin mentioned in the email sent to the maintainers.

The fact that the editors aren't listed in the citation provided by Zenodo is, I think, a bug/missing feature on their end. It might be worth opening an issue with them to let them know. From a quick check, it seems that the editors are listed in some citation formats but not others.

@libcce, text for the titles and abstracts to include in the release would be helpful

**Comment by ostephens** [comment]
Thanks @fmichonneau

>your preference in AMY is set to "No" for the option "Consent to include name when publishing lessons". If you wish to be included in future releases, please update your preference in your AMY profile.
I can't currently login to AMY (I don't think I've ever logged in tbh). I sent emails to team@carpentries.org and you to try to resolve this but received no reply.

Please do add my name to the release

Obviously we should respect preferences in AMY, but I would want to double check that @pitviper6, @ccronje and @partiecolored all of whom are editors on this lesson and have made significant contributions really don't want to be credited as creators.

>The fact that the editors aren't listed in the citation provided by Zenodo is, I think, a bug/missing feature on their end. It might be worth opening an issue with them to let them know. From a quick check, it seems that the editors are listed in some citation formats but not others.
Not sure where this would need raising, or what citation format is being used - can you advise?

**Comment by libcce** [comment]
@ostephens @fmichonneau A follow-up message to contributors would be helpful IMHO. Many can't keep up/track of the messages. 

Regarding Zenodo citation export, I'm not sure this an issue on their end. It would be too difficult for them to track all the different requests for styles, that's why they tap into CSL and allow for export in multiple formats. We would have to use a citation tool like Zotero to do this. The MARCXML export happens to work (editor metadata is included) via Zotero import as XML file. However, it is a manual process for adding some missing metadata back like the DOI or correcting metadata. Our citation style seems to be a combination of book chapter/software. We can create a Carpentries citation style (CSL) that can be imported into Zotero for use. I wonder if we can have this conversation in the broader Maintainers group?

**Comment by ErinBecker** [comment]
Thanks for letting us know about the issue @ostephens. We definitely want everyone to get credit for their contributions. 

I've toggled your AMY profile to allow listing you as a contributor when publishing lessons. You should also be able to log-in with your GitHub ID (I responded to your previous email to try to get your GH ID but maybe it went to your spam?) 

I'm digging around in Zenodo now to see which citation styles they support that list editors. I mistakenly used their default citation format in my last email to the Maintainers group and should have checked around editors first. I'll follow up here and in an email to Maintainers with information about citation format and to let people know how to get themselves added to the release if they don't appear. Thanks again for telling us of the problem.

**Comment by libcce** [comment]
@fmichonneau after consulting with the CAC, I started removing "...for librarians" from lesson titles. So this one is now "Library Carpentry: OpenRefine". I may have missed some cases so may have not caught this before it was published.

**Comment by ErinBecker** [comment]
Re-reading what @libcce wrote above about citation formats, I see now that just toggling to a different citation format probably isn't the solution (and none of the ones I've tried has had editors listed). It looks like we may need to go the short-term --> long-term route by asking Maintainers to manually add editors to the citation in their lesson repo and then (longer-term) creating a Carpentries citation style as @libcce suggested above. I'm hesitant to ask Maintainers to do yet another thing manually, but it's better than not showing up in the list at all! Anyone have any other suggestions to explore?

**Comment by ostephens** [comment]
Thanks @ErinBecker for sorting out my AMY profile - I've now logged in OK

And thanks @libcce @ErinBecker @fmichonneau for working on the overall question of citations and getting creators credited

**Comment by katrinleinweber** [comment]
For completeness & posterities sake: https://amy.carpentries.org/dashboard/trainee/autoupdate_profile/ > "Do you consent to have your name or identity associated with lesson publications? is the place to enable this :-)

**Comment by ErinBecker** [comment]
Yes, thank you @katrinleinweber!

**Comment by libcce** [comment]
@ostephens should we close this? Or did you want to reach out to contributors and point them to https://amy.carpentries.org/dashboard/trainee/autoupdate_profile/?

**Comment by ostephens** [comment]
Thanks @libcce - I've reached out to @pitviper6 @ccronje @partiecolored specifically and flagged this conversation to them. I'll close

Thanks all
