### ISSUE TITLE
"Make sorts permanent" no longer an option in open refine 3.1

### ISSUE THREAD

**Issue by grynoch** [LibraryCarpentry/lc-open-refine#41]
I don't know if this is true for OpenRefine 3.2 beta, but for  OpenRefine 3.1 there is no option in the sort menu to make sorts permanent. Where would be the best place to note this in the Working with columns and sorting section or in the instructor notes?

**Comment by ostephens** [comment]
@grynoch OpenRefine 3.1 still has the option to make sorts permanent. This is the "Reorder rows permanently" option in the Sort drop down menu (once you have applied a sort).

Can you check, and if you aren't seeing this option describe exactly what you are doing?

I can see that the episode on using sorts (https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/_episodes/06-working-with-columns.md) is very sparse - do you think it could be improved? If so, what information would you want to see added?

**Comment by ostephens** [comment]
@grynoch I'm going to close this for now as I can't replicate the problem you describe. If you think it is still an issue, please feel free to re-open the issue with additional detail (screenshots illustrating the problem would be great).

Thanks

**Comment by katrinleinweber** [comment]
In case the above turns out to be true, here's one improvement suggestion to the lesson: https://github.com/LibraryCarpentry/lc-open-refine/compare/gh-pages...TIBHannover:41-remove-permanent?expand=1

**Comment by katrinleinweber** [comment]
Ah, never mind. The option is in a different dropdown:
![grafik](https://user-images.githubusercontent.com/9948149/63583796-fc006d80-c59b-11e9-9a46-c9158917bbad.png)

**Comment by katrinleinweber** [comment]
☝️ possibly useful answer to

> … episode on using sorts … could be improved?

Please feel free to cherry-pick.

**Comment by libcce** [comment]
@katrinleinweber do you want to reopen this issue and link it to another issue?

**Comment by katrinleinweber** [comment]
No, I just wanted some place to refer to my changes. I'm currently preparing to teach it in early Sept. Maybe I'll send some PRs afterwards.

You could also create [(a) big one(s)](https://github.com/LibraryCarpentry/lc-open-refine/compare/gh-pages...TIBHannover:proof-read) as an alternative to both waiting for me, and to cherry-picking.
