### ISSUE TITLE
Add Episode on Dates in OpenRefine

### ISSUE THREAD

**Issue by ostephens** [LibraryCarpentry/lc-open-refine#61]
Based on request by @rovinghistorian in #10 
@rovinghistorian said:
>Would there be time in lesson 10--or would it be better as part of an advanced set of lessons--to discuss handling transforming messy dates? (My use case: a spreadsheet inventory with a column for dates, creators added data like 2/xx/1954 or 19?? in addition to 2/3/1934 and other data that was easier to transform/clean up.)

@ostephens replied
>I think a lesson on "Dates in OpenRefine" that could be optionally included would be v useful . Would be interesting to sketch out what could be in that - but would think about including:

> * Using toDate and toString
> * Using 'match' to work with messier dates
> * Date facets
> * Date specific GREL functions: datePart, diff, inc, now

**Comment by jas58** [comment]
Retiring/closing, as there now is an extension for TidyData, https://librarycarpentry.org/lc-spreadsheets/, which includes date topics.
