### ISSUE TITLE
Seeing different data in 'Put titles into Title Case'

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-open-refine#65]
In Writing Transformations > Put titles into Title Case, I saw something different than what is written in the exercise. I don't see the publisher selections in uppercase. Can someone confirm? As an alternative, we can include an additional step to Edit Cells > Common transforms > To uppercase (to make sure the publisher names are in uppercase)?

**Comment by ostephens** [comment]
It's the Titles associated with the selected Publishers that are uppercase - not the publishers themselves

The exercise correctly says to select lines based on publisher (via a facet), and then do the transform on the Title column
