### ISSUE TITLE
How do you start OpenRefine?

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-open-refine#68]
In this [lesson](https://librarycarpentry.org/lc-open-refine/02-importing-data/index.html) it says:

> To import the data for the exercises below, run OpenRefine. NOTE: If OpenRefine does not open in a browser window, open your browser and type the address http://127.0.0.1:3333/ to take you to the OpenRefine interface.

We don't show anywhere how you actually start OpenRefine.

**Comment by libcce** [comment]
@maneesha this is covered in the setup https://librarycarpentry.org/lc-open-refine/setup.html. In the Data Cleaning with OpenRefine lesson for Ecologists there is a pointer to getting started. Is this what you are suggesting, something similar?

**Comment by maneesha** [comment]
Got it.  Maybe it would help to have a link to that included in the lesson?

**Comment by ostephens** [comment]
We already have a link to the Setup in episode 2, but specifically in the context of downloading the data to use in the lesson. I think the link could be repositioned to be at the top of the section in episode 2 to generally point the user to setup before they start the exercise.

**Comment by morskyjezek** [comment]
I agree that it can be somewhat odd for first-time OR users, but as has been pointed out the information is there in the lesson. It seems mostly an issue of how to clearly point it out. In that spirit, and Working on a suggestion for my instructor checkout process, it may be possible to add in as an objective for the episode? I've made a possible suggestion here https://github.com/LibraryCarpentry/lc-open-refine/pull/74.

**Comment by libcce** [comment]
@maneesha does this https://github.com/LibraryCarpentry/lc-open-refine/pull/77 address https://github.com/LibraryCarpentry/lc-open-refine/issues/68#issue-448212535 ?

**Comment by maneesha** [comment]
Works for me - thanks!
