### ISSUE TITLE
Add step to Importing Data into OpenRefine episode 

### ISSUE THREAD

**Issue by jenchaput** [LibraryCarpentry/lc-open-refine#70]
In the "Importing Data into OpenRefine" episode, the "Create your first OpenRefine project (using provided data) exercise does not include a step to retitle your project.  OpenRefine will automatically name it based on the file name, which may or may not be useful. 

I did my teaching demo last week as part of the instructor checkout process, and actually hadn't done the lesson contribution yet, which was great in that it allowed me to go back and notice that this was actually missing from the exercise. The Caprentries' staff member that led my teaching demo session commented on my not renaming the project as I demo'd this lesson, and I had assumed I missed a step only to find it's not there. 

I've attached a screenshot with the Project name field circled in blue to distinguish it from the red circles on the current version of the lesson. I'd recommend adding a red circle for this section too, and add a step in the numbered exercise steps. Maybe make this step 7? 

![open_ref_title_addition1](https://user-images.githubusercontent.com/43176212/58571681-42963400-8208-11e9-831f-1d9b79ad4a59.JPG)
![open_ref_title_addition2](https://user-images.githubusercontent.com/43176212/58571693-45912480-8208-11e9-9cb4-ae7177a2e876.JPG)

**Comment by libcce** [comment]
Thanks @jenchaput ! I think it would be good to add this as an additional step. Can you suggest what the step would say either through a pull request or via this issue? I'm not sure about the extra circle though.

**Comment by jenchaput** [comment]
My suggestion for the additional step: 
"The Project Name box in the upper right corner will default to the title of your imported file. Click in the [project name] box to give your project a different name, if desired." 

I suggest making this the new Step 7, and then Step 8 will be "Once you are happy..."

**Comment by libcce** [comment]
Thanks @jenchaput!
