### ISSUE TITLE
Lesson #4 - Faceting and Filtering

### ISSUE THREAD

**Issue by erinjerome** [LibraryCarpentry/lc-open-refine#75]
I noticed that this lesson starts with facets, briefly touches on filters, and then returns to facets.  For the sake of continuity and grouping like concepts together, I thought the page might benefit from a slight reordering:
 
1. Facets
2. Let's create a text facet
3. Facet exercise (Which licenses are used for articles in this file?)
4. More on facets
5. Facet exercise (Find all publications without a DOI)
6. Filters
7. Working with filtered data

I’d also like to suggest changing “More on Facets” to “Going beyond the text facet”.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

**Comment by ostephens** [comment]
Hi @erinjerome - thanks for this suggestion.

The reason that the lesson is ordered as it is is that Text Facets and Text Filters are by far the most common tools that most people will use to filter the data. My view is that it is important to see these as two aspects of the same thing - they are both ways of narrowing down the set of data that is being worked with.

Also note that the "Working with filtered data" section actually refers to any set of filtered data - that could have been done by selecting values in a facet or by using a text filter - so I think it is correct to have this earlier in the lesson - it's really important to understand this aspect of OpenRefine before you start making changes on filtered data sets.

There is always room for improvement, and we should definitely consider if the structure of the lesson could be improved. However, given this lesson has been taught successfully many times, I'm reluctant to support a change unless it is driven by clear evidence that the current structure doesn't work in some way (e.g. feedback from students that it was confusing) or that the new structure will be better.

I think re-naming the "More on Facets" would be fine, although I think maybe we should perhaps be more explicit - maybe "Other types of Facet" would be a more straightforward heading? I think this more accurately describes the content of the section.

**Comment by libcce** [comment]
@ostephens +1 to changing "More on Facets" to "Other types of Facet". As you say, seems like a more straightforward heading. Regarding the ordering of the episode, I'd agree with you as well, that we would need to hear from more instructors that this is an issue, otherwise, I've seen this order being taught successfully on a number of occasions.

**Comment by erinjerome** [comment]
@ostephens thanks for the quick reply!  I missed the reference to any set of filtered data in the "Working with filtered data" section, so apologies for that.  I definitely support changing "More on Facets" to "Other types of Facets".

**Comment by libcce** [comment]
Thanks @erinjerome for the suggestion 😄 Also, thanks @ostephens for submitting https://github.com/LibraryCarpentry/lc-open-refine/pull/76 which has been merged.
