### ISSUE TITLE
Lesson #04 Faceting and Filtering 

### ISSUE THREAD

**Issue by frankiestevens** [LibraryCarpentry/lc-open-refine#82]
Suggested improvements to the text of the Faceting and Filtering Lesson of the Library Carpentry Open Refine course:

	• Question > How can I use filters and facets to explore data OpenRefine?
		○ Question > How can I use filters and facets to explore data **in** OpenRefine?
	• Facets are one of the most useful features of OpenRefine and can help both get an overview of the data in a project as well as helping you bring more consistency to the data.
		○ Facets are one of the most useful features of OpenRefine and can help **in** both gett**ing** an overview of the data in a project as well as helping you bring more consistency to the data.
	• A ‘Facet’ groups all the values that appear in a column, and then allow you to filter the data by these values and edit values across many records at the same time.
		○ A ‘Facet’ groups all the values that appear in a column, and then allow**s** you to filter the data by these values and edit values across many records at the same time.
	• Correct the Language values via a facet > Text facet on the language column and correct the variation in the EN and English values.
		○ Correct the Language values via a facet > **Use the** Text facet on the language column and correct the variation in the EN and English values.

**Comment by ostephens** [comment]
Thanks very much @frankiestevens 

>How can I use filters and facets to explore data **in** OpenRefine?
@phillypb are you able to add this change to your current PR on Lesson 4?

>Facets are one of the most useful features of OpenRefine and can help **in** both gett**ing** an overview of the data in a project as well as helping you bring more consistency to the data.
@frankiestevens I agree this sentence could be improved, but I'd suggest a different phrasing. What do you think of:
"Facets are one of the most useful features of OpenRefine and can help to get an overview of the data and to improve the consistency of the data."

>A ‘Facet’ groups all the values that appear in a column, and then allow**s** you to filter the data by these values and edit values across many records at the same time.
@phillypb has already made this change in #80 

>Correct the Language values via a facet > **Use the** Text facet on the language column and correct the variation in the EN and English values.
I'd suggest "Create a" rather than "Use the". What do you think @frankiestevens?

**Comment by frankiestevens** [comment]
I'm happy with all of your suggestions @ostephens :-)

**Comment by libcce** [comment]
@ostephens if you want to review https://github.com/LibraryCarpentry/lc-open-refine/pull/122 should be good to go 👍

**Comment by bencomp** [comment]
It appears this issue was resolved with #122 and can be closed.
