### ISSUE TITLE
Lesson #3: Rows vs. Records with lengthy metadata files

### ISSUE THREAD

**Issue by mchartier2992** [LibraryCarpentry/lc-open-refine#84]
Good morning!

My name is Madison Chartier.  I'm a new hopeful instructor with the Carpentries and look forward to being a part of this group.

I'm presently doing a lot of work in my job with OpenRefine.  It's a great tool (I love it!), but I've run across some issues that I was curious whether or not might be beneficial to address or acknowledge in Library Carpentry lessons as potential troubleshooting areas when working with lengthy, messy metadata files on OpenRefine.  One issue in particular is the concept of "Rows" and "Records," as discussed in Lesson #3 of the Library Carpentry: OpenRefine session.

The CSV files I often clean on OpenRefine are set up to contain one record per row.  However, when uploading more extensive files (say, with 10,000 entries), I've noticed that OpenRefine tends to glitch or misread some of the records, mistaking some rows as being related when they are meant to be their own unique entries.  In such instances, the "Records" view winds up being misleading, and I'm often obliged to ignore it.  I end up relying exclusively on the "Rows" view, which tends to reflect the more accurate count of entries from the start.

Has anyone else encountered this issue?  If so, is there an explanation for it?  Might it be something we want/need to address when working on OpenRefine with the particular kind of data we're often obliged to work with in libraries?  I'd be curious to know your thoughts.

Thanks!

Regards,
Madison

**Comment by ostephens** [comment]
Hi @mchartier2992. I think there are two parts to this:

>The CSV files I often clean on OpenRefine are set up to contain one record per row. However, when uploading more extensive files (say, with 10,000 entries), I've noticed that OpenRefine tends to glitch or misread some of the records, mistaking some rows as being related when they are meant to be their own unique entries

>Has anyone else encountered this issue? If so, is there an explanation for it? Might it be something we want/need to address when working on OpenRefine with the particular kind of data we're often obliged to work with in libraries? I'd be curious to know your thoughts.

I think these questions would be great ones to raise on the OpenRefine mailing list (http://groups.google.com/forum/#!forum/openrefine) or on the OpenRefine github https://github.com/openrefine/openrefine/issues

I'm sure you won't be the only person to have encountered these issues but by reporting to the wider OpenRefine community you stand the best chance of getting some investigation done (I'm also part of that community and help develop OpenRefine so I'll probably get involved anyway, but I think that's the right venue)

**Comment by ostephens** [comment]
Secondly:
> I was curious whether or not might be beneficial to address or acknowledge in Library Carpentry lessons as potential troubleshooting areas when working with lengthy, messy metadata files on OpenRefine. One issue in particular is the concept of "Rows" and "Records," as discussed in Lesson #3 of the Library Carpentry: OpenRefine session.

I think having approaches to trouble shooting would be valuable - for Rows/Records, but also in other lessons. I think the important thing is helping people think about how they approach troubleshooting and working out what is going wrong and that they know how to try out different things to fix it and where to go for help if they don't successfully resolve the problem themselves.

 I wonder if this might be best addressed as part of the Instructor notes rather than necessarily having it as part of the delivered material? I'm not altogether sure to be honest - part of my concern of adding it to the lesson material is that it pushes the length of the lesson overall.

**Comment by libcce** [comment]
@mchartier2992 what language would you suggest for the instructor notes https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/_extras/guide.md? Or @ostephens is this something that is mentioned on the OpenRefine site?

**Comment by ostephens** [comment]
To be honest there isn't great information on the Records concept on the OpenRefine site - the only place they are given any real space is https://github.com/OpenRefine/OpenRefine/wiki/Variables as far as I know.

I tend to point people at the LC lesson!

**Comment by ostephens** [comment]
The updated OpenRefine documentation now has a good explanation of Rows vs Records https://docs.openrefine.org/manual/exploring#rows-vs-records

**Comment by jas58** [comment]
Can this suggestion, "Craft a sentence or two for instructor notes about Rows vs Records" become a "help wanted" or "good first issue"? 
from 
Rows vs Records https://docs.openrefine.org/manual/exploring#rows-vs-records become a "help wanted" or "good first issue"?

**Comment by ostephens** [comment]
@jas58 yes I think so - although I think I'd be in favour of it being in the main lesson text as it's just a link to the official documentation. 

I'd suggest two new issues arising from this one (which we could then close):

1. As you suggest an issue to add something either to the the instructor notes or the main lesson text pointing to the Rows vs Records section in the OpenRefine manual - this would be a good first issue
2. An issue relating to the concept of adding troubleshooting advice to the lesson and if this is desirable and how this might be approached

Does that sound OK?

**Comment by jas58** [comment]
Yes, agreed.  I'll create those PRs, referencing this discussion and marking them as good first issues.

**Comment by ostephens** [comment]
Thanks @jas58. I think #227 is definitely a good first issue. I'm not sure #228 is as I think it's quite challenging to know how to offer advice on how to troubleshoot - I'd be in favour of removing the label from that one

**Comment by jas58** [comment]
I removed the GFI label from 228.
