### ISSUE TITLE
OpenRefine 3.2

### ISSUE THREAD

**Issue by felixlohmeier** [LibraryCarpentry/lc-open-refine#91]
[OpenRefine 3.2](https://github.com/OpenRefine/OpenRefine/releases/tag/3.2) was released on Friday.

I have done the lesson side by side with 3.1 and 3.2 and cannot see any differences. Even advanced functions (fetching urls from crossref, viaf reconciliation, vib-bits extension) work the same way as before. I suggest to change the "latest tested version" in https://github.com/LibraryCarpentry/lc-open-refine/blob/gh-pages/setup.md to 3.2.

OpenRefine 3.2 introduces some new features (cf. https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.2) but in my point of view there are no "game changers" and it is better to maintain the backwards compatibility of the lesson for now.

**Comment by ostephens** [comment]
Thanks so much for testing this @felixlohmeier - that's great to know.

If anyone wants to make a PR for changing the latest tested version that would be great

**Comment by libcce** [comment]
Thanks @felixlohmeier PR is ready https://github.com/LibraryCarpentry/lc-open-refine/pull/92 @ostephens want to merge?
