### ISSUE TITLE
Episode 3: Layout of OpenRefine, Rows vs Records

### ISSUE THREAD

**Issue by jomtov** [LibraryCarpentry/lc-open-refine#93]
Hi,
I am Joakim Philipson from Stockholm University. As a new  prospect Carpentry instructor, this is my first issue as part of the checkout process:

[Episode 3](https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html)

Suggest a minor change of wording here:

> You will now see that split rows have gone away - the Authors have been joined into a single cell with the specified delimiter. Our Rows and Records values will now be the same since we do not have any more ~~split columns~~.

to be replaced by:

> ... columns with split (multi-valued) cells

Motivation for suggested change: 
- Reference back to previously used expression, (multi-valued) might be left out
- Avoid possible confusion and misunderstanding that *columns*, not cells, were split before

**Comment by ostephens** [comment]
Thanks @jomtov for raising this issue!

Completely agree this should be changed. If anyone wants to make a pull request for this change then please go ahead

**Comment by libcce** [comment]
Fixed via https://github.com/LibraryCarpentry/lc-open-refine/pull/101
