### ISSUE TITLE
Episode 9: Transformations - Undo and Redo

### ISSUE THREAD

**Issue by jomtov** [LibraryCarpentry/lc-open-refine#95]
[Episode 9](https://librarycarpentry.org/lc-open-refine/09-undo-and-redo/index.html) 

To:

> If you wish to save a set of steps to be re-applied later, or to a different project, you can click the Extract button. This gives you the option to select the steps you want to save, and to copy the transformations included in the selected steps in a format called ‘JSON’

suggestion add:

> You can copy the Extracted JSON and save as a simple text-file (e.g. in Notepad) for later re-use. 
> (Tips: save with a filename that helps you remember the steps involved, for example
> _authorSplitANDmassEditPublisher.txt_ )

Motivation for suggested addition: it is not clear now how to save selected steps,  and it also might give the impression that the file has to be saved as _xxx.json_

**Comment by ostephens** [comment]
Thanks @jomtov 

I think the sentence about pasting and saving in a file is a good addition. I’m slightly less sure about the tip in file naming as I think people should be free (and are able) to decide on their own naming / filing process - but I maybe being too picky!

I think a PR to make this change would be great

**Comment by dpdong19** [comment]
Thank you for the suggestion! I agree that making the proposed changes may cause less confusion. However I think direct addition may make it a bit lengthy and repetitive. May I suggest merging the original and the added part with some wording changes as below: 

"If you wish to save a set of steps to be re-applied later, or to a different project, you can click the Extract button. This gives you the option to select steps that you want to save, and extract the codes for those steps in a format called ‘JSON’. You can copy the extracted JSON and save it as a simple text file (e.g. in Notepad)."
I also agree with @ostephens that perhaps we can leave out the file naming suggestion here - even though itself is an important matter worthy of separate discussion. We may want to be less prescriptive here and keep it concise. What do you think?

**Comment by libcce** [comment]
Thanks @dpdong19 I've created a PR based on your nice suggestion https://github.com/LibraryCarpentry/lc-open-refine/pull/123

@ostephens or someone else want to review/approve?

**Comment by ostephens** [comment]
Closed by #123
