### ISSUE TITLE
Suggestion for Episode 2 Importing data into OpenRefine

### ISSUE THREAD

**Issue by mikaelalawrence** [LibraryCarpentry/lc-open-refine#97]
This is a suggested change to a lesson as part of checkout as a new instructor. https://librarycarpentry.org/lc-open-refine/02-importing-data/index.html
It took time to understand the import conditions for numbers 4-6 and it took me a while to find an explanation for number 6. Also, not including “Use character “ to enclose cells containing column separators” did trip me up in the teaching demo. I didn't take notice of this condition while teaching myself OpenRefine.

Current instructions
4. Click in the Character encoding box and set it to UTF-8
5. Ensure the first row is used to create the column headings by checking the box Parse next 1 line(s) as column headers
6. Make sure the Parse cell text into numbers, dates, ... box is not checked, so OpenRefine doesn’t try to automatically detect numbers

Suggested changes to make the above statements specific to the demo dataset. 
4. Click in the Character encoding box and set it to UTF-8 as it will ensure the special characters in the Author column are displaying correctly
5. Ensure the first row is used to create the column headings by checking the box Parse next 1 line(s) as column headers
6. OpenRefine will automatically select “Use character “ to enclose cells containing column separators” as this will place data in one cell where the values are enclosed in quotes from the source dataset
7. Make sure the Parse cell text into numbers, dates, ... box is not checked, so OpenRefine doesn’t try to automatically detect numbers as it may cause errors such as confusion between American and British date formats

Thanks

**Comment by libcce** [comment]
Thanks @mikaelalawrence for the suggestion! Would you mind submitting a pull request to make these changes?

**Comment by mikaelalawrence** [comment]
@libcce Thank you I have now submitted a pull request with the changes.

**Comment by bencomp** [comment]
I think this issue was resolved by PR #119 and follow-up PR #166 (from @ostephens).
